### ISSUE TITLE
[Arquitectura] Posibilidad de front-end en React

### ISSUE THREAD

**Issue by B-Dominguez** [IIC2113-2020-2/Recursos#11]
Hola, quisieramos saber si está permitido / les parece aconsejable que para el proyecto separemos front-end (React App) y back-end (Rails app expuesta como api). Nuestro tema es Exchange.

Desde ya gracias!

**Comment by cnscheihing** [comment]
Hola Benja!

Sí estará permitido desarrollar el frontend de la app en otra tecnología como React, y desarrollar el backend en Rails expuesto como una API (tal como señalas). El diagrama de arquitectura que incluyan en la documentción de la entrega 1 debe reflejar esta decisión. Del mismo modo, si en algún momento del desarrollo del proyecto realizan otro cambio, deberán actualizar su documentación.

Espero haberte ayudado!

**Comment by B-Dominguez** [comment]
Gracias Claudio! Queda clarísimo
