### ISSUE TITLE
Diagrama de Componentes [Database]

### ISSUE THREAD

**Issue by chris-carstens** [IIC2113-2020-2/Recursos#12]
Hola!

Para el Diagrama de componentes, se requiere integrar la base de datos como un componente directamente, o se debe relacionar a través de algún componente que integre estos datos?

Gracias!

**Comment by movaldivia** [comment]
Hola @chris-carstens !

Para el diagram de componentes puedes hacer algo como esto:

![image](https://user-images.githubusercontent.com/24725124/92241747-c1a6fd00-ee8c-11ea-810a-46560fb7afa6.png)

El acceso al la base de datos es el ORM (Active Recort en Rails)
