### ISSUE TITLE
Instalación VS

### ISSUE THREAD

**Issue by jmndoza** [IIC2113-2020-2/Recursos#13]
Hola,
Para la instalación de VS que es necesario marcar en mac/win ? 

![2020-09-04 10 56 59](https://user-images.githubusercontent.com/24240983/92253415-777a4780-ee9d-11ea-8dc4-479c88bcace3.jpg)

![2020-09-04 10 56 43](https://user-images.githubusercontent.com/24240983/92253397-6fbaa300-ee9d-11ea-9b35-f6b145f7707b.jpg)

**Comment by movaldivia** [comment]
@jerrymendoza 

Cuando lo instalé creo que con esto bastaba.

![image](https://user-images.githubusercontent.com/24725124/92271824-76094900-eeb6-11ea-9ada-ea60481cb86b.png)
