### ISSUE TITLE
Preguntas de materia Prueba 1

### ISSUE THREAD

**Issue by perojas3** [IIC2113-2020-2/Recursos#14]
1.- No entiendo los diagramas de objetos (diagramas 8) ¿Que estan representado y para qué sirven?

2.- No entiendo la forma en que los diagramas de tiempo (diagramas 12) funcionan. ¿Como enfatisan los cambios de estados?

3.- Tampoco entiendo los diagramas de perfil (diagramas 14). En nada, no sé porque se llaman así, y que es lo que representan.

4.- Sobre el modelo 4+1. Sé que menciona 5 vistas, pero no entiendo la forma en que se inteconectan, ni como se puede utilizar para ayudar a mejorar el desarrollo de software.

5.- Sobre TPM, los 5 principios. ¿En qué consiste el principio Seiri (organización, convensiones de nombre)?

6.-Sobre los principios SOLID. El princpio S. "Single Reponsability". ¿Porque el logging es un error? ¿Y porqué un factory arregla la serialización?

7.-Sobre los principios SOLID. El princpio O. "Open-Closed". En general no lo entiendo. Eso de estar abierto a extension y no a modificación. ¿A que se refiere? ¿Acaso extender una clase no es modificarla? ¿Y porque eso ayuda a la mantenibilidad a largo plazo de un proyecto?

8.- Sobre los principios SOLID. El princpio D. "Dependency Inversion". Este no lo entiendo completamente. Y el ejemplo es muy pequeño para entenderlo bien. ¿Me podria ayudar?

9.- Sobre todos los principios SOLID, me da la duda si seguirlos efecticamente disminuye la complejidad el 100% del tiempo.

10.- Sobre las metricas de calidad. ¿En "Transición del Producto" y "Operación del Producto" en que consiste la Interoperabilidad?

11.- No entiendo como medir el Responde for Class (RFC). Digo, la descripción simplemente lo hace ver como la cantidad de metrodos publicos. ¿Como seria?

12.- No entiendo el problema del bloater "Long Method", y me parece que el  numero de 10 lineas de codigo es muy poco. Ejemplo: ¿Realmente mover codigo a un nuevo metodo disminuye la complejidad si solo se utilizara una sola vez?

13.- No entiendo nada del bloater "Data Clumps".

**Comment by movaldivia** [comment]
@perojas3 
1.) Los diagramas de objetos sirven para representar una _foto_ del software en un tiempo determinado. Enseña instancias y no clases. ¿Para qué sirve? Sirve para dar ejemplos de relaciones que podrían ser difíciles de describir con un diagrama de clases ya que te puedes ayudar con los valores de los atributos.

2.) Enfatizan el cambio de estado cuando la linea negra cambia de un espacio amarillo a otro, como en la imágen:
![image](https://user-images.githubusercontent.com/24725124/92425595-13d27180-f15e-11ea-9147-a93f4f46b08f.png)

6.) Tal como dice el principio una clase debería tener una sola responsabilidad, imagínate que comprar monedas, luego si además se encarga de loggear datos de la compra ya tendría dos responsabilidades: comprar monedas e imprimir información -> luego no se sigue el principio

7.) Imaginate un código con millones de líneas, sin test y alto acomplamiento. Luego si modifico un método no podría saber a ciencia cierta si voy a romper otra parte de la aplicación, por ello, en vez de modificar algo que funciona es preferible extender y lograr algo nuevo.

9.) Los principios solid son estándares de alta calidad, pero claro no te van a garantizar el 100% del tiempo reducir la complejidad/tiempo/costo. Por ejemplo, una analogía que se me ocurre es realizar un desarrollo monolítico contra uno serverless, este último cumpliría el principio Single responsability, pero podría ser más complejo para el desarrollador. En conclusión, son una "pauta" a tener muy en cuenta, pero no por eso se utilizan el 100% del tiempo. 

12.) El número 10 es un corte que se ha visto en la práctica como bueno, pero no es un regla "oficial", por ejemplo, tu podrías definir 15 lineas en rubocop. La tendencia es que se puede reducir la complejidad porque puedes juntar código donde la función da una buena idea de lo que hace ese segmento

13.) La idea es no repetir el mismo set de variables en muchas partes del código. Un caso que se me ocurre es cuando tienes variables de configuración que usas en varias partes del software, donde la solución es crear un objeto que contenga todas las variables de configuración
