### ISSUE TITLE
Video Ayudantía/Actividad

### ISSUE THREAD

**Issue by Marialuisaclaro** [IIC2113-2020-2/Recursos#16]
Hola!
No fui a la Ayudantía del Viernes y estaba viendo el video. ¿Existe la grabación de la Parte 2? ¿O dónde puedo ver el enunciado de la Actividad?

Ojalá puedan subir la segunda parte para los que no pudimos asistir!
Gracias!!

**Comment by movaldivia** [comment]
@Marialuisaclaro El enunciado de la actividad está en canvas en la parte de tareas
![image](https://user-images.githubusercontent.com/24725124/92408297-73eff600-f113-11ea-9757-b99a71a28b09.png)
Entras y sale enunciado.

Respecto a la segunda parte, no sé si @cnscheihing la subirá, pero fue más un "pregunten" respecto al enunciado.

**Comment by B-Dominguez** [comment]
Hola! Al final de la parte 1 dicen que hubo hartas preguntas (y respuestas) por el chat. Cuando uno graba una reunión de zoom, junto al archivo mp4 se guarda un .txt con el chat. ¿Podrían por favor subirlo? Si fuera así, creo que podría ser útil para los que no pudimos asistir en vivo.

Gracias!

**Comment by movaldivia** [comment]
@B-Dominguez Estimado lo acabo de sumir a canvas en el módulo ayudantía 1

**Comment by B-Dominguez** [comment]
Gracias!!
