### ISSUE TITLE
[Actividad 1] Problemas con subir el archivo a Canvas

### ISSUE THREAD

**Issue by miguelramirezv** [IIC2113-2020-2/Recursos#17]
Hola! Espero que estén muy bien.

Estoy teniendo un problema en tratar de subir el archivo a Canvas. He intentado subir el archivo solo .cs y el .zip, pero en ambos casos me sale: "Hubo un error en la entretela; intente de nuevo". 

¿Qué puede estar pasando?

Muchas gracias!!

**Comment by movaldivia** [comment]
@miguelramirezv por un tema de orden intenta mañana, si mañana no te funciona a las 20:00 tienes permiso para enviármelo por mail a movaldivia@uc.cl con copia del error.

**Comment by miguelramirezv** [comment]
Gracias @movaldivia , no sé que habrá pasado pero hoy logré subirlo! 

Muchas gracias por tu disposición!!
