### ISSUE TITLE
Uso de librerías en C#

### ISSUE THREAD

**Issue by gicrot** [IIC2113-2020-2/Recursos#18]
Hola, me surgió la duda de si para la actividad, y más bien para la prueba, podemos utilizar librerías dentro de C#. 
Esto lo pregunto porque al hacer la actividad encontré que el uso del objeto List me ayudaba a realizar una parte más facilmente, especificando como comentarios el qué hacía respectivamente y para la cual lo abrí instanciando:
````
using System.Collections.Generic;
````

**Comment by movaldivia** [comment]
@gicrot No hay problema que lo uses, a menos que se explicite que no la uses.
