### ISSUE TITLE
[Interrogación] Explique cómo llegó a su conclusión...

### ISSUE THREAD

**Issue by benjastraub** [IIC2113-2020-2/Recursos#19]
Hola, no me queda claro cómo esperan que expliquemos cómo llegamos a nuestra conclusión.

¿Tenemos que explicar qué contenidos utilzamos o explicar qué aspectos tomamos en cuenta, etc?

Si pudieran ejemplificar sería genial.

**Comment by mf222** [comment]
Hola Benjamín,

Ojala ambos, al menos explicar el contenido que utilizaste, los aspectos que tomaste en cuenta serían buenos de tener también, pero si explicaste cómo el contenido te ayudo sería lo mismo.

Un ejemplo sería este: 

Pregunta: ¿Cómo está el clima hoy?
Respuesta: Soleado, con 16ºC. **Llegue a esta conclusión porque miré por la ventana y revisé la página accuweather donde salían 16º**.

Lo que esta en negrita es explicar cómo llegue a la conclusión. El objetivo es no dar la respuesta a secas, si no explicar el proceso que utilizaste para llegar a esa conclusión. Para efectos del curso, en vez de mencionar "la página accuweather" mencionar la materia relacionada ("según la clase de UML cuando se hablaba de diagramas de despliegues aparecia que ...", "según la lectura de Grinders vs Thinkers decia que los Grinders...", etc.-), o si de verdad se te ocurrió sin la materia, o hiciste un proceso mental, justificar por qué se te ocurrió así. En el ejemplo, sería "porque miré por la ventana, y porque cuando hace más de 20 grados siento calor con mi chaqueta puesta, y cuando hay menos de 15 siento frio. Como estoy con la chaqueta y casi a punto de tener frio, deben haber como 16 grados" -> ojo que este tipo de respuestas es más subjetiva, ojala que prefieran basarse en algo que hayamos visto en el curso.
