### ISSUE TITLE
[Interrogación] Pregunta 2 b) re-escribir código en otro lenguaje

### ISSUE THREAD

**Issue by meretamal** [IIC2113-2020-2/Recursos#20]
Hola 😄

En la pregunta 2 b), al re-escribir el código, este debe estar en c#, tal como el ejemplo, o puede estar en ruby?

**Comment by mf222** [comment]
Hola Moisés,

Puede estar en Ruby, pero en tal caso el código tiene que seguir siendo funcional, piensa que estás "corrigiendo" el código (la ventaja de escribir en C# es que no vas a tener que re-escribirlo todo desde 0, si no que solo lo editas).

**Comment by meretamal** [comment]
Buenísima 😄

Gracias!!
