### ISSUE TITLE
[Interrogación] Código pregunta 2b

### ISSUE THREAD

**Issue by Dnpoblete** [IIC2113-2020-2/Recursos#21]
Hola, no se si yo estoy haciendo algo mal, pero al tratar de correr el código de la pregunta 2 me aparece este error "error CS0136: A local or parameter named 'm' cannot be declared in this scope because that name is used in an enclosing local scope to define a local or parameter", entonces no se si es parte de lo que tenemos que arreglar o si es un error que no estaba contemplado.

Gracias 😄

**Comment by mf222** [comment]
Hola @Dnpoblete ,

Hay que arreglarlo. Ojo que dado que lo publicaste, si alguien arregla este bug dentro de los 3 problemas pedidos "dado que no se ejecuta" no es suficiente (ya que se hizo publica la respuesta).

**Comment by Dnpoblete** [comment]
Uhh perdón por decirlo, pero pesaba que estaba mal porque en la pregunta dice que el código como esta ahí es funcional, pero no compila :sweat_smile:

**Comment by Cadagan** [comment]
Hola! solo como idea, podrían subir un anuncio para avisarle a la gente que si considero esto como uno de los 3 problemas que ya no se puede considerar como uno, para que alcancen a arreglarlo en caso de que lo necesiten 😉

**Comment by mf222** [comment]
@Cadagan no hay problema irá en la pauta, y la modifiqué para no "descontar" por esto. Se considerará bueno este punto si lo mencionan en el sentido que se cambió el nombre de la variable debido a los quality design guideliness o debido a que hace abuso del nombre de las variables (no mencionando solo porque se cae). Si alguien no lo llega a arreglar, pero arregla otros errores de la calidad del código también se considerará correcto.
