### ISSUE TITLE
[Interrogación 1] Pregunta 3.d.

### ISSUE THREAD

**Issue by fivaldivia** [IIC2113-2020-2/Recursos#22]
Hola, quería saber a que se refiere en cuanto a la pregunta : Su amigo no sabe lo que es UML. ¿De qué forma podría explicarle el diseño de la aplicación con el fin de que entienda? 
Hay que explicar sobre qué es UML, o buscar algún diagrama que le explique el diseño de la aplicación?
Gracias!

**Comment by mf222** [comment]
> buscar algún diagrama que le explique el diseño de la aplicación

Si encuentras un diagrama que alguien que no sabe entienda el diseño de la aplicación, es un camino.

El objetivo es que uses tu criterio/ingenio para explicarle a alguien que no sabe de UML. Si crees que explicándole UML es la forma, justificalo bien.
