### ISSUE TITLE
[Interrogación 1] [Pregunta 2b)]

### ISSUE THREAD

**Issue by NicolasLahsen** [IIC2113-2020-2/Recursos#24]
En esta pregunta, debo solucionar uno de los problemas identificados en el punto anterior. Mi duda es si el problema es pequeño y la solución es un cambio pequeño también, estaría resolviendo el problema que identifiqué, pero de todas formas el código sigue siendo muy mejorable. ¿Esta bien este enfoque, o el código debe quedar claramente mejor?
Muchas gracias!

**Comment by mf222** [comment]
Si el cambio pequeño se ve reflejado en todo el código y el script funciona, entonces está bien. 

Pero ojo, que está relacionada con la pregunta 2.a. Si en la 2.a. señalaron mejoras de forma vaga (o que no sean posibles implementar), probablemente la van a tener mala.
