### ISSUE TITLE
Seiri y Seizo duda interrogación

### ISSUE THREAD

**Issue by dhvasquez** [IIC2113-2020-2/Recursos#25]
Hola, estaba buscando un poco más de información acerca de los TPM, y encontre en internet que Seiri significa eliminiar del espacio de trabajo lo que sea inutil (en los ppt ese seria el significado de Seiso).

¿Cuál es el correcto?

**Comment by mf222** [comment]
Gracias por notarlo. Efectivamente en las diapos cometí un error e invertí los nombres.

A pesar de lo anterior, para efectos de la prueba y la materia se entiende que lo importante no es el nombre, si no que el principio por detrás (de hecho, no se les ocurra hablar _en la vida real_ en base a los nombres japoneses de TPM, porque nadie les va a entender). Ninguna pregunta espera que respondan Seiri o Seiso a secas, si no que explicaran el significado detrás del principio.
