### ISSUE TITLE
[Ejercicio I1] Nombres de películas

### ISSUE THREAD

**Issue by cacoos** [IIC2113-2020-2/Recursos#28]
Hola!

Podemos asumir que los nombres de las películas no tendrán variaciones? Es decir, siempre aparecerá "The Joker" y no "The joker", "THE JOKER", etc.?

Gracias!

**Comment by mf222** [comment]
Hola, 

No, existirán variaciones en cuanto al string en mayus y minus entre las distintas fuentes de datos. Eso sí, pueden asumir que no existirán variaciones en cuanto a caracteres especiales (letras con tilde por ejemplo).

Si existen variaciones del tipo "El Joker" y "El Joker de Todd Phillips" o "El Guasón" considérenles como películas diferentes.

**Comment by cacoos** [comment]
Gracias! Entonces nosotros escogemos cuál de todos los nombres mostrar (según las variaciones de May-Min) o seguimos alguna convención?

**Comment by mf222** [comment]
Críterio de ustedes. Pero mi recomendación, de acuerdo a la materia del curso, es que definan una convención.
