### ISSUE TITLE
[I1 Parte 2] Bloaters

### ISSUE THREAD

**Issue by matumartinez** [IIC2113-2020-2/Recursos#29]
Hola

¿Qué tan exigentemente se van a evaluar los bloaters? Por ejemplo, ¿si un método tiene más de 10 líneas se descuenta de forma automática? Lo pregunto porque pueden haber métodos que requieran ejecutar el mismo comando varias veces, como el caso de Console.Writeline() cuando haya que hacer la interacción con la consola.

Saludos

**Comment by mf222** [comment]
Sí, se descontará. Existen varias formas de arreglar ese tipo code smells como el que mencionas.

**Comment by juanfcolopez** [comment]
Me queda una duda sobre las 10 líneas del método,  
de dónde comienzan a contar? desde que se plantea el nombre del método? o desde que se abren las llaves?

public void Function()
{
    línea 1
}

0

linea 1 public void Function()
linea 2{
            linea 3
...
}

Saludos.

**Comment by matumartinez** [comment]
A mi también me quedan dudas:

¿Se cuentan las lineas en blanco, o solo las que tengan código?

Si hago algo de este estilo:

string string_largo = "
stringsuperhipermegalargo";

¿Cuenta como una línea o dos?

¿Las líneas contadas consideran tanto ejecución de algún comando como declaración de variables?

**Comment by mf222** [comment]
@juanfcolopez se considera lo que esté dentro del bloque (vale decir los `{}`). De la materia del curso, esto no es una petición arbitraria de que consideren el tamaño de sus funciones, recuerden que la cantidad de líneas en un método habla de un code smell.

@matumartinez solo se cuentan las líneas con código. Recuerden que estamos midiendo complejidad y definiendo las responsabilidades de cada método y clase. Un documento vacío tendría 0 complejidad, al igual que un método vacío (algo del tipo `public void Function() {}`). Sobre la segunda pregunta, depende de cómo se lea la línea, pero dudo que si tienes un linter activo te lo considere como bien escrito, de hecho ese tipo de quiebre afecta la lectura del código. Te recomiendo que lo dejes en una sola línea.

Finalmente, les recomiendo que **investiguen sobre lint y analizadores de código** (lo mencioné en la clase que vimos las métricas de código). Ya sea para C# como para Ruby (y les pasó el tip de FxCop y Rubocop respectivamente).
