### ISSUE TITLE
Formato Wireframes

### ISSUE THREAD

**Issue by chris-carstens** [IIC2113-2020-2/Recursos#3]
Hola!
Teníamos una pregunta, ¿cuál es el formato esperado de los wireframes?
Con mi grupo pensamos en hacerlo directamente en html, con lo que incluiríamos el frontend que podríamos usar posteriormente.
No sé si es más de lo esperado, o se busca algo distinto. O quizás también está incluído en unos de los bonus mencionados respecto al frontend de la página.

Saludos y gracias!

**Comment by mf222** [comment]
Hola Chris,

Un html es mucho más de lo esperado. Les pido un wireframe de baja fidelidad, es similar a esto:

![image](https://user-images.githubusercontent.com/5504289/90967807-ac0bfd80-e4b2-11ea-9fa2-13b97cee05ef.png)

Otro ejemplo más artesanal de wireframe de baja fidelidad es este:

![image](https://user-images.githubusercontent.com/5504289/90967820-ce9e1680-e4b2-11ea-89ec-d4204cb9fb08.png)

Un html me da la impresión de que apunta más a ser un prototipo o mockup. Les recomiendo esta lectura [https://www.mockplus.com/blog/post/wireframe-mockup-prototype-selection-of-prototyping-tools](https://www.mockplus.com/blog/post/wireframe-mockup-prototype-selection-of-prototyping-tools)

La idea de la entrega 1 es que no corran a programar, sin antes aterrizar la solución (por eso el plazo es tan corto).

**Comment by chris-carstens** [comment]
Bacan, se entiende.

De todos modos, la idea iba para "adelantar" un poco de pega, en el sentido de en vez de hacerlo en balsamiq, hacer una versión estática de un par de vistas altiro con html + css, que si bien es más pega, nos sirve tanto de wireframe o diseño/estructura preliminar como también de base del frontend para la siguiente entrega.
Quizás es algo a la larga contraproducente y conviene mucho más asegurarse con algo más básico y mutable, como balsamiq (por eso la pregunta)

Gracias profe!
