### ISSUE TITLE
[Ejercicio I1] Más de 1 calificación en 1 película

### ISSUE THREAD

**Issue by miguelramirezv** [IIC2113-2020-2/Recursos#30]
Hola! Tenía una duda de cuando una usuario califica 2 veces una misma película usando la plataforma Nadeje. En ese caso, la segunda evalución se considera como:

> Una nueva calificación

> Una actualización de la primera calificación

Al ser finalmente mi calificación, me hace sentido que se actualice pero igual me quiero asegurar porque perfectamente podría ser la otra. 

Muchas gracias!!

**Comment by mf222** [comment]
Será la actualización de la primera calificación.

**Comment by pbyoma** [comment]
Se borraría la calificación anterior o hay que sacar un promedio entre la antigua y la nueva?
