### ISSUE TITLE
[Ejercicio I1] Partes que suponemos seran cambiadas en el futuro

### ISSUE THREAD

**Issue by perojas3** [IIC2113-2020-2/Recursos#31]
Entiendo que en general de las buenas practicas y los principios SOLID, tengo que considerar que espero va a ser cambiado en el futuro, para adaptarme a eso. Dentro de la simulación que es el ejercicio ¿Que se espera que va a ser cambiado?

**Comment by mf222** [comment]
Podría cambiarse todo, esa incertidumbre es parte del desarrollo de software. Por lo anterior, procura que el código siga de la mejor manera posible a lo visto en clases.
