### ISSUE TITLE
[Ejercicio I1] Modificar archivo json

### ISSUE THREAD

**Issue by juakoke** [IIC2113-2020-2/Recursos#32]
¿Puedo modificar a mano el archivo rotten.json?, específicamente  ¿Puedo cambiarle el nombre a la llave "critics consensus" por "critics"? Pregunto ya que cuando paso a deserializar el archivo, no puedo definir variables en C# con espacio, como critics consensus.

**Comment by mf222** [comment]
Sí, puedes hacer. Sin embargo, los que hagan lo anterior a nivel de código frente a modificar el archivo tendrán un pequeño bonus en la sección que evalúa buenas prácticas.
