### ISSUE TITLE
[Ejercicio I1] Solución Modular

### ISSUE THREAD

**Issue by juanfcolopez** [IIC2113-2020-2/Recursos#33]
Hola!

Tengo una duda de enunciado. Cuando dice que nuestra solución tiene que ser modular se refiere a que todo el código lo tenemos que tener en distintos archivos e ir importándolos según lo que se vaya haciendo necesario? o solo a que en un archivo tengamos todas las funcionalidades bien separadas según las buenas prácticas y principios?

Muchas gracias

**Comment by mf222** [comment]
Lo primero, archivos separados. Un solo gran archivo es difícil de procesar y leer, en especial cuando ya programan soluciones más grandes y complejas.

**Comment by juanfcolopez** [comment]
Comprendo
Muchas gracias.
