### ISSUE TITLE
[Ejercicio I1] Entrega de solución

### ISSUE THREAD

**Issue by nmaturana97** [IIC2113-2020-2/Recursos#34]
Hola, 

¿Esta bien si entrego el proyecto completo de visual studio en un .zip, o solo tengo que entregar los archivos *.cs?

En caso de que sea la segunda opción, ¿cómo nos aseguramos que la corrección tenga los archivos *.json en la misma ruta que señalamos en nuestro código?

**Comment by mf222** [comment]
Sube los .cs y los .json juntos en el .zip.

Puedes además añadir el proyecto completo de visual estudio en una carpeta separada para facilitar la importación, pero es opcional, lo importante son los .cs.
