### ISSUE TITLE
[Ejercicio I1] Tipo de dato "year" MetaCritic

### ISSUE THREAD

**Issue by daleal** [IIC2113-2020-2/Recursos#35]
Hola! El archivo `metactitic.json` contiene objetos que tienen un atributo `"year"`. En casi todos los objetos, `year` es de tipo `int`, excepto por el primer objeto, donde es de tipo `string`. Eso es algo que debería ocurrir, o fue un error en la creación del `json`?

**Comment by mf222** [comment]
Lo puedes cambiar directo en el .json. Sin embargo, los que hagan el arreglo a nivel de código frente a modificar el archivo tendrán un pequeño bonus en la sección que evalúa buenas prácticas.

**Comment by Marialuisaclaro** [comment]
Hola @mf222 !
Esto puede ocurrir en cualquiera de los archivos? o solo en el metacritic? puede pasar en cualquiera de las variables?
(Nose si nos evaluarán con los mismos archivos o otros)

Saludos y gracias!
