### ISSUE TITLE
gemas ruby

### ISSUE THREAD

**Issue by nrrosenberg** [IIC2113-2020-2/Recursos#36]
Hola, se pueden ocupar gemas de ruby para la parte práctica? 
(Quiero ocupar la gema json para leer y parsear los archivos de las películas)

**Comment by mf222** [comment]
Sí, ocupen todo lo que les acomode. No re-inventen la rueda. 

Eso si, traten de ser evidentes si hay que instalar alguna dependencia extra para que el ayudante corrector no piense que simplemente no compila.

**Comment by nrrosenberg** [comment]
Donde podemos dejar alguna instrucción para correr el programa o instalar alguna dependencia??
Hacemos un README?

**Comment by mf222** [comment]
@nrrosenberg si estas usando Ruby, quedaría _bonito_ si lo haces con un gemfile. Aquí hay un ejemplo para facilitar la instalación con bundler https://bundler.io/guides/bundler_in_a_single_file_ruby_script.html

**Comment by perojas3** [comment]
Yo estoy pensando hacer lo mismo en c#. Asumire que alli tampoco hay problema.

**Comment by jonatanmurga** [comment]
> Donde podemos dejar alguna instrucción para correr el programa o instalar alguna dependencia??
> Hacemos un README?

**Comment by jonatanmurga** [comment]
> Sí, ocupen todo lo que les acomode. No re-inventen la rueda. 
> 
> Eso si, traten de ser evidentes si hay que instalar alguna dependencia extra para que el ayudante corrector no piense que simplemente no compila.

**Comment by jonatanmurga** [comment]
> Hola, se pueden ocupar gemas de ruby para la parte práctica? 
> (Quiero ocupar la gema json para leer y parsear los archivos de las películas)

**Comment by jonatanmurga** [comment]
> Yo estoy pensando hacer lo mismo en c#. Asumire que alli tampoco hay problema.
