### ISSUE TITLE
[Ejercicio I1] Duda Principio SOLID: S single responsability

### ISSUE THREAD

**Issue by perojas3** [IIC2113-2020-2/Recursos#37]
Ok estoy haciendo el ejercicio, y me surge la siguiente duda sobre uno de los principios SOLID.
Especificadomente la S, Single Responsability.
Mi problema es que no estoy seguro del significado de la Responsabilidad en el contexto de dasarrollo de software.
En el caso extremo, si cada acción seria una responsabilidad "la responsabilidad de tomar esa acción", cada clase o guardaria estado, o tendria un unico metodo. Pero creo que esa no es la idea
¿Bajo que contexto algo es una Responsabilidad?

Y con esto me surge una segunda duda. Si una responsabilidad no incluye guardar estado. ¿Es ok que todos los metodos de esa clase sea estaticos?

**Comment by mf222** [comment]
Hola Pablo,

Es una responsabilidad en la medida que hace sentido con el problema que se resuelve. Por ejemplo un auto debería tener la responsabilidad de "moverse, retroceder" pero "poner música" podría estar fuera de su contexto. Para eso es mejor tener una clase Radio que ponga la música (y el auto posea una Radio).

Creo que es una pregunta muy buena, y te recomiendo leer este artículo del autor de SPR [https://blog.cleancoder.com/uncle-bob/2014/05/08/SingleReponsibilityPrinciple.html](https://blog.cleancoder.com/uncle-bob/2014/05/08/SingleReponsibilityPrinciple.html)

En este artículo explica en detalle el varios puntos que en la primera definición quedaron vagos, cómo definir cuánto modularizar. Rescato esta frase:

> Gather together the things that change for the same reasons. Separate those things that change for different reasons.

Sobre la segunda pregunta, sí, si no guardas ningún dato, es mejor que definas los métodos estáticos, así evitas instancias innecesarias. Cuando creo métodos estáticos suelo pensarlos como "funciones que no van a cambiar y que su pega es solo ayudar sin diferenciación sobre a quién ayuda".
