### ISSUE TITLE
[Ejercicio I1] Archivos Json

### ISSUE THREAD

**Issue by NicolasLahsen** [IIC2113-2020-2/Recursos#38]
Hola!

¿Debemos considerar que los archivos json puedan venir incompletos? Por ejemplo que no todos los objetos vengan con calificación, o año, o podemos asumir que vendrán completos como los ejemplos

**Comment by mf222** [comment]
Hola Nicolas,

Consideren que vendrán con todas las keys, pero que podrían haber algunas con valores nulos o vacios ("").
