### ISSUE TITLE
[Ejercicio I1] Calificación del usuario - Tipo de dato

### ISSUE THREAD

**Issue by tfflores** [IIC2113-2020-2/Recursos#39]
Hola,
Me surgió una duda con respecto a la calificación del usuario. Sabemos que utiliza una escala de 1 a 5, ¿esta escala sólo acepta calificaciones enteras?

Es decir, ¿debo considerar sólo válidos los inputs enteros de 1 a 5 o también tengo que aceptar los números decimales en ese rango?

**Comment by mf222** [comment]
Hola @tfflores,

Definan ustedes eso y sean consistentes con la decisión que tomen. En un inicio planeaba forzarlos a que considerarán decimales, pero al final preferí dejarlo a elección. Por lo mismo, la decisión que tomen debe considerar los casos bordes: si deciden que solo acepta int, definan qué pasará si un usuario pone un 2.5 en la consola (qué mensaje mostrará). Si deciden que pueden ser decimales, tengan ojos con los cálculos y con la precisión.
