### ISSUE TITLE
Consulta Wireframes E1

### ISSUE THREAD

**Issue by aleuribej** [IIC2113-2020-2/Recursos#4]
Hola!
Teníamos una duda con mi grupo por el tema donde se pide dos wireframes. ¿Hay que ocupar dos distintos, por ejemplo, Balsamiq y otro más? ¿O se refiere a que hay que hacer dos en "Balsamiq", pero desde distintos "puntos de vista",como usuario registrado y administrador? ¿O iba a otro punto totalmente distinto?
Que nos entro esa duda! 🙌

Muchas gracias de antemano 😄

**Comment by mf222** [comment]
Hola @aleuribej 

Me refiero a representar dos "screenshots" de lo que será su aplicación. Por ejemplo en ambos temas se pide que el usuario pueda ver sus transacciones (¿cómo debería ser esa interfaz de forma general? ¿qué datos va a tener? ¿cómo se van a mostrar?); 

Luego otra funcionalidad de la aplicación es que debe permitir que usuario pueda tranzar/transferir. En ese sentido esas serían dos interfaces distintas (porque si le saco una foto a la aplicación en esos dos momentos, lo que verá el usuario será distinto). Piensen que es similar a sacarle una captura de pantalla a su aplicación en algún momento.

Ojo que Balsamiq no es sinonimo de wireframe. No confundan mockup o prototipo con lo que es un wireframe. Te recomiendo darle un vistazo a este otro issue también #3  en este recomiendo una lectura al final, les dejo el link por si se les escapa

[https://www.mockplus.com/blog/post/wireframe-mockup-prototype-selection-of-prototyping-tools](https://www.mockplus.com/blog/post/wireframe-mockup-prototype-selection-of-prototyping-tools)

**Comment by aleuribej** [comment]
Ahhh ya entiendo, ahi revise también la issue #3 que dijo y claro ahora me quedo más clara la idea que se busca.
Que finalmente no es necesariamente hacer un flujo full completo como el que se puede hacer en Balsamiq sino que algo más como las "screenshots" que mencionaba.  
Y por otro lado, efectivamente tenia la confusión entre el mockup y el wireframe, habia pensado que eran casi lo mismo jajaja

Muchas gracias profe por su ayuda! 🙌😄
