### ISSUE TITLE
[Ejercicio I1] Peliculas a mostrar - critics consensus

### ISSUE THREAD

**Issue by perezpefaur** [IIC2113-2020-2/Recursos#40]
Hola! Tengo dos preguntas del enunciado:
1) "Debes crear un programa que al ejecutarse, lea de estos archivos e imprima en pantalla la lista de todas las películas que se encuentran en los 3 archivos" hace referencia a que la película se crea solo si el titulo esta en los tres archivos simultáneamente o basta en que este en uno para ser creado.
2) critics consensus es equivalente summary/descripcion, ya que encuentro que es mas como una reseña que una descripcion.

**Comment by mf222** [comment]
Hola @perezpefaur,

1.- Basta que esté en uno de los 3 para ser creado.
2.- No es la descripción, es la reseña. De cualquier forma entiendo que se pueda dar a confusión, si alguien lo considera como descripción no lo consideraremos malo (pero a priori no era la idea que lo usaran como descripción).

**Comment by meretamal** [comment]
Hola 😁 

En ese caso, si la película solo aparece en _rotten tomatos_, está bien si dejamos la descripción en blanco?
