### ISSUE TITLE
[Ejercicio I1] Problemas con usar la clausura(programación funcional) y bloaters

### ISSUE THREAD

**Issue by perojas3** [IIC2113-2020-2/Recursos#41]
Estoy en C#, en mi caso uso las keyword Action y Func para definir funciones dentro de otra función, de esa manera puedo evitar repetir código.
Sé que este ramo de programación orientada a objetos, por eso estoy tomando las precauciones de solo hacer esto dentro de un mismo modulo o clase, para disminuir al máximo el acoplamiento.
Mi duda es como esto interactúa con el bloater de una función muy larga, una función es declarada dentro de otra, ¿Se suman la cantidad de líneas de código para este bloater?
En algunos casos puedo quitar la función y colocarla como un método privado normal de la clase, pero esto no deja claro que es una función hecha exclusivamente para ser usada por un método.
Pero en otros no puedo hacerlo porque hace uso de la clausura de la función.
¿Que me recomienda?

**Comment by mf222** [comment]
Hola Pablo,

No entendí muy bien tu pregunta. De paso, te recomiendo evitar sobre complejizar las soluciones. Te respondo lo que sí entendí:

> Mi duda es como esto interactúa con el bloater de una función muy larga, una función es declarada dentro de otra, ¿Se suman la cantidad de líneas de código para este bloater?

Depende de la métrica, si es solo LOC (lines of code) entonces si se suman. Si es por complejidad, se toma como 2 procedimientos separados y ahí se calculan. Por lo anterior, sí, afecta al code smell de bloater.

En general recomiendo ser lo más claro cuando vayas a usar una función, si dejarla fuera de la función inicial ayuda a que se entienda mejor, entonces dejala fuera. 

Si estas trabajando en C# o Ruby, dado que es orientado a objetos, considero (en mi opinión) poco práctico usar funciones dentro de funciones. A diferencia de Javascript en que la lógica es totalmente distinta y más que necesario hacerlo. Por lo anterior, no existe una regla general y dependerá totalmente del contexto y el lenguaje que estás usando.
