### ISSUE TITLE
[Ejercicio I1] Convención de paths

### ISSUE THREAD

**Issue by arpincheira** [IIC2113-2020-2/Recursos#42]
Hola, como va a ser la corrección en términos del uso de los paths en nuestras entregas? Resulta ser que al utilizar Visual Studio para poder acceder a un archivo con la ruta: ```./nombre``` este se debe encontrar dentro de una carpeta dentro de las dependencias del proyecto, pero dado que nosotros debemos mandar solamente los archivos .cs no sabría exactamente si considerar ese path como uno válido o si puedo asumir que los ayudantes modificarán de alguna manera los paths para evitar problemas al momento de correr el código según como lo hagan(tengo entendido que hay otros editores que si te permiten usar ese path sin problemas).

De antemano muchas gracias

**Comment by jmndoza** [comment]
@arpincheira mi ~~humilde~~ idea, es que si ocupas una ruta relativa como la que indicas, no importara si entregas solo el archivo cs, piensa que el cs se debe compilar y la ruta la toma desde donde este el archivo compilado y ejecutado, ahi la razón que vs lo toma desde debug o release (si lo cambias)
