### ISSUE TITLE
Invitación repo base

### ISSUE THREAD

**Issue by nrrosenberg** [IIC2113-2020-2/Recursos#43]
Hola, estaba intentando aceptar la invitación para el repo base pero ya esta invalida, podrían enviarmela de nuevo por favor?

**Comment by movaldivia** [comment]
@nrrosenberg Listo!

**Comment by chuma9615** [comment]
A mi tambien porfa!

**Comment by movaldivia** [comment]
@chuma9615 contacto con tu ayudante de proyecto, yo no te puedo invitar S:
