### ISSUE TITLE
Modifcación del repo base

### ISSUE THREAD

**Issue by tomascortes** [IIC2113-2020-2/Recursos#44]
Hola!
Según las instrucciones del repo base nosotros debemos instalar ciertos programas para poder utilizarlo con rails, pero con nuestro grupo nos bajó la duda si eso es lo que se supone que tenemos que hacer o agregar la parte de Rails utilzando docker (que este dentro de un contenedor específicamente). 
Y si este no es el objetivo aprovecho de preguntar si es recomendable, para otros proyectos. 

Gracias!

**Comment by mf222** [comment]
Hola Tomás,

Lo que más les acomode. En general dockerizar todo es buena opción para la portabilidad, sin embargo y dadas las restricciones de tiempo, háganlo solo si disponen de ese tiempo (dado que no será evaluado, y tampoco hay bonus al respecto). En caso de dockerizar, deben ser específicos al momento de documentar.
