### ISSUE TITLE
Duda device controller en repo base.

### ISSUE THREAD

**Issue by oscars810** [IIC2113-2020-2/Recursos#45]
Hola!

Si bien en el repo base está instalado `device`, quería saber porque no estan los controladores de este.

**Comment by mf222** [comment]
Hola Oscar,

Device propone una forma de armar los controladores, pero la gracia de usar la gema es como maneja la sesión, no la estructura que obliga a usar. La libreria viene incluida ya que es dependencia de otra gema que está pre-configurada (ActiveAdmin, similar al admin de Django para los que programan ahí). 

Si necesitan los controladores de device, créenlos.
