### ISSUE TITLE
Problemas con ./bin/setup (docker)

### ISSUE THREAD

**Issue by miortiz1** [IIC2113-2020-2/Recursos#46]
Luego de clonar el repositorio  en la consola de comandos de linux subsystem parto docker con "sudo service docker start"
Despues intento correr "./bin/setup" y me tira 4 exceptions (las 4 tienen que ver con docker) y termina con:

--> "  File "docker/api/client.py", line 213, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))
[603] Failed to execute script docker-compose"

Intento correr "sudo dockerd" y me sale al final el siguiente error
--> "failed to start daemon: Error initializing network controller: error obtaining controller instance: failed to create NAT chain DOCKER: iptables failed: iptables -t nat -N DOCKER: iptables v1.6.1: can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded."

(Por si sirve tambien:
Al intentar: "sudo docker ps"
--> Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?)

Mi versión de docker: Docker version 19.03.13, build 4484c46d9d

**Comment by movaldivia** [comment]
@miortiz1 no conozco el problema, pero tienes instalado docker con las versión de wsl2?
Asi:

![image](https://user-images.githubusercontent.com/24725124/94605719-e1ed9000-026f-11eb-8650-1e260bb6e0c5.png)

**Comment by miortiz1** [comment]
No se donde ver eso
Eso es de docker desktop?

No tengo lo tengo intente descargarlo pero me decía que no cumplía los requisistos de windows 10 pro, tengo el home.
No me calenté mas la cabeza pq pensé que tener el desktop no me iba a servir en linux susbsystem

**Comment by movaldivia** [comment]
Llego así:

click derecho barquito blanco (docker) y luego
![image](https://user-images.githubusercontent.com/24725124/94610924-68f23680-0277-11eb-8ace-18a82f414164.png)


Con el correo de la universidad puedes conseguir windows educational:

![image](https://user-images.githubusercontent.com/24725124/94610973-79a2ac80-0277-11eb-8e15-be41a9bfb4ed.png)

Te recomiendo instalar wsl2

**Comment by miortiz1** [comment]
Instalé wsl2, actualice windows y descargue docker desktop y cambió el error, ahora tengo este:
![image](https://user-images.githubusercontent.com/37181021/94632708-b1264e80-02a1-11eb-85fb-84b6e40a8154.png)
Busque en internet e reistalé docker desktop pero nada... mismo error
Tambien hice configuraciones en /.docker/config.json, hice cambions al config.json en la carpeta de docker y nada...

Varias horas despues de empezar a escribir este comentario al parecer lo logre arreglar corriendo:
sudo  ln -s /mnt/c/Program\ Files/Docker/Docker/resources/bin/docker-credential-desktop.exe /usr/bin/docker-credential-desktop.exe
Hasta ahora funciona
