### ISSUE TITLE
[Ejercicio I1] Calificación Nadeje

### ISSUE THREAD

**Issue by marianaortega1** [IIC2113-2020-2/Recursos#48]
Hola!

No me queda claro qué hacer en cuanto a la calificación Nadeje. Debo guardarla en algún archivo para que cuando otro usuario entre le muestre la calificación definitiva considerando las calificaciones Nadeje? o se pierde nomás?

También, si no hay datos de algunas fuentes (ej imbd o metacritic) entonces no los considero nomás para la calificación definitiva y promedio solo los que tienen datos ? 

Saludos!

**Comment by valerojasm** [comment]
+1 por la primera pregunta
