### ISSUE TITLE
./bin/setup problemas con bin/rails db:setup

### ISSUE THREAD

**Issue by tpcantergiani** [IIC2113-2020-2/Recursos#49]
Hola,
Al correr el comendo `./bin/setup`, tengo el siguiente error:
![image](https://user-images.githubusercontent.com/44327650/95259994-61460b00-07fe-11eb-80e6-c6ed57620a88.png)
Intente reiniciando postgres, pero no he podido arreglarlo.
Gracias!

**Comment by mf222** [comment]
Si estás corriendo tu aplicación directamente, revisa si está corriendo el servidor de postgres en el puerto correcto. Trata reiniciando el servidor de postgres si es que está bien el puerto. Si tienes problemas para reiniciar, corrobora de que no haya algún archivo que te este bloqueando la sesión.

Si estás corriendo tu aplicación en docker, comprueba que tienes el contenedor corriendo para postgres y que dentro de tu aplicación se está apuntando correctamente a cada contenedor. A veces cuando tienes docker y postgres instalados, si no están bien configurados puede que tu aplicación rails no sepa a cuál está accediendo.
