### ISSUE TITLE
Cuentas Tema 1

### ISSUE THREAD

**Issue by benjastraub** [IIC2113-2020-2/Recursos#5]
Hola, como grupo tenemos unas dudas sobre las cuentas para el tema 1:

- ¿puede un usuario tener más de una cuenta? por ejemlpo si el usuario quisiera comprar Badtheriums, ¿estos serían una cuenta a parte de las que Bitfakes o todos los balances van en una cuenta?
- en caso de que sea más de una cuenta ¿es el usuario el que se hace partner o alguna de las cuentas? por ejemplo, ¿puede mi cuenta de Bitfakes ser Partner pero la de Badtheriums no?

**Comment by mf222** [comment]
Hola Benjamín,

> ¿puede un usuario tener más de una cuenta? por ejemlpo si el usuario quisiera comprar Badtheriums, ¿estos serían una cuenta a parte de las que Bitfakes o todos los balances van en una cuenta?

Es **solo una cuenta de usuario por correo/rut/dirección de la cuenta y un solo saldo en CLP**. Sin embargo los balances deberían ser distintos. No estaría bien mezclar los balances de compra y venta de Badtheriums junto con los de Bitfakes por ejemplo. Cada uno debería ser contabilizado de forma paralela.

> en caso de que sea más de una cuenta ¿es el usuario el que se hace partner o alguna de las cuentas? por ejemplo, ¿puede mi cuenta de Bitfakes ser Partner pero la de Badtheriums no?

Es solo una cuenta, por lo que la cuenta del usuario se asocia a una sola cuenta de usuario.
