### ISSUE TITLE
Error al ejecutar rails s

### ISSUE THREAD

**Issue by fivaldivia** [IIC2113-2020-2/Recursos#52]
Hola hace tiempo hice el setup del proyecto en mi computador y ejecuté ```rails s```para correrlo y me funcnionó bien. Ahora, cuando ejecuto ```rail s```me tira un error en el localhost, y buscando en internet parece ser un error de postgres pero no entiendo porque ya que no lo tengo instalado. Este es el error:
```
        could not connect to server: Connection refused
	Is the server running on host "127.0.0.1" and accepting
	TCP/IP connections on port 5432?
```
Gracias!

**Comment by mf222** [comment]
Si estás corriendo tu aplicación directamente, revisa si está corriendo el servidor de postgres en el puerto correcto. Trata reiniciando el servidor de postgres si es que está bien el puerto. Si tienes problemas para reiniciar, corrobora de que no haya algún archivo que te este bloqueando la sesión.

Si estás corriendo tu aplicación en docker, comprueba que tienes el contenedor corriendo para postgres y que dentro de tu aplicación se está apuntando correctamente a cada contenedor. A veces cuando tienes docker y postgres instalados, si no están bien configurados puede que tu aplicación rails no sepa a cuál está accediendo.
