### ISSUE TITLE
Duda sobre enunciado del proyecto

### ISSUE THREAD

**Issue by matumartinez** [IIC2113-2020-2/Recursos#53]
Hola!

Hay dos cosas que dicen que van a evaluar que no entiendo muy bien cómo:

1) "pull requests" acotados: ¿Se refiere sobre pull requests a la rama master, en ese caso cuántos pull requests máximo?

2) Revisión de código entre pares: no entiendo en qué consiste y cómo van a hacer para evaluarlo.

Saludos

**Comment by mf222** [comment]
>"pull requests" acotados: ¿Se refiere sobre pull requests a la rama master, en ese caso cuántos pull requests máximo?

Se refiere **acotados en extensión no en cantidad**. Ojala que si usan git flow, los pr's de las ramas de trabajo respondan a una funcionalidad, la indicación es para que eviten pr's del tipo "todo el proyecto en una pr". Aquí de nuevo aclaro, si usan gitflow se entiende que desde su rama de desarrollo a la estable hagan una sola gran pr, pero el trabajo sobre su rama de desarrollo debió haber sido a través de pequeñas pr's por funcionalidad. Si no usan gitflow, el codigo que vayan mergeando debe ir todo en pr's que expliquen "qué es lo que están mergeando".

> Revisión de código entre pares: no entiendo en qué consiste y cómo van a hacer para evaluarlo.

A través de las pull-requests, la idea es que se revisen entre ustedes. De acuerdo a lo que ya vieron en el ramo de ingeniería de software, deberían saber como trabajar con pull-requests y code review. En el caso de que no lo recuerden, haré un ejemplo de cómo funcionan los pull-request y el code review. 
Imagina que eres compañero de Pepito. Se dividieron en trabajo en partes, tu hacer el login y Pepito hace un formulario. Terminaste de hacer el login, lo que haces es subir en una rama de github tu trabajo y de esa rama haces un pull request. Le pides a Pepito que haga la revisión. Pepito leera tu código, si está excelente lo aprobará y te dirá que está bien. Si encuentra que hay cosas raras, que no entiende o si hay algún error lo comentará. Así tu y Pepito iteraran el código que estás por subir hasta que ambos esten conformes, entonces Pepito lo aprueba y se mergea a su rama estable. Luego harán lo mismo con la funcionalidad de Pepito. Dicho lo anterior, el equipo docente revisará el github y el repositorio (los commits, pull requests y comentarios que hagan), y en base a lo anterior irá parte de la nota.

**Comment by matumartinez** [comment]
Gracias por la respuesta, pero hay unas cosas que debo aclarar sobre ingeniería de software. No sé si será igual para todos, pero en mi caso (di el ramo el 2019-2) no nos enseñaron pull requests, yo lo aprendí a hacer pero por cuenta propia. En cuanto a code review, lo debimos haber visto en la cátedra muy de pasada, pero en el proyecto nunca se pidió code review (por lo que recién ahora aprenderé cómo trabajar con esto).
