### ISSUE TITLE
¿Donde están las views de log in y sign up?

### ISSUE THREAD

**Issue by matumartinez** [IIC2113-2020-2/Recursos#54]
Hola!

Noté que la plantilla del proyecto viene con los modelos de user y admin_user ya creados, además de las vistas de log in y sign up ya hechas. ¿Donde se pueden encontrar estas vistas en el proyecto? Necesito agregarle atributos a rellenar en el form de usuario.

Saludos

**Comment by mf222** [comment]
El login que existe es de una gema llamada ActiveAdmin. Tienen que crear ustedes el login y registro de los usuarios, es parte del enunciado del proyecto.

**Comment by matumartinez** [comment]
¿Tenemos que crear a mano el registro y login de usuarios?

**Comment by Marialuisaclaro** [comment]
Hola! Existe una migración DeviseCreateUsers. Esa migración no crea automaticamente todo?

**Comment by chuma9615** [comment]
Yo tengo la misma duda, no se si fue un error del primer commit incluir las migraciones o estan intencionalmente ahi por un motivo que desconozco, podrian aclararlo por favor?
