### ISSUE TITLE
Manejar commits y aprovarlos entre si

### ISSUE THREAD

**Issue by perezpefaur** [IIC2113-2020-2/Recursos#55]
He visto esta documentacion en donde explican como aprobar commits y revisar el codigo, pero como no existe un rol de administrador del repo no se puede. Tampoco podemos organizarnos como un team en github lo que nos imposibilita hacer revision del codigo a traves de github. Mando los links que lei de la documentacion:
https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/about-pull-request-reviews#required-reviews
https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-organizations-and-teams/managing-code-review-assignment-for-your-team

**Comment by mf222** [comment]
@perezpefaur la documentación que envías es para configurar la asignación automática de miembros. Les recomiendo que lo hagan manual. En especial ya que son equipos pequeños, les resultará mucho más fácil coordinarse entre ustedes para asignar, ya que como equipo deben tener una conversación fluida.

Al costado de la pull request eligen a alguien del equipo
![image](https://user-images.githubusercontent.com/5504289/96280172-09ea2c80-0fae-11eb-8ab3-757e449aa4a6.png)
![image](https://user-images.githubusercontent.com/5504289/96280191-0eaee080-0fae-11eb-9b5a-4844e54a9eb5.png)

Luego esa persona puede revisar el pr y añadir sus comentarios
![image](https://user-images.githubusercontent.com/5504289/96280290-2b4b1880-0fae-11eb-9938-2ac0a06a19c2.png)
