### ISSUE TITLE
[Entrega 2] Tema 2: Fondo de Inversiones

### ISSUE THREAD

**Issue by marianaortega1** [IIC2113-2020-2/Recursos#56]
Hola!

Hemos leído varias veces el tema 2 Banco de Inversiones y nos quedan dudas sobre cómo funcionan las cuentas de ahorro y el fondo de inversión. Se nos ocurren varias formas de ver el problema:

1. Uno envía dinero desde la cuenta normal a la cuenta de ahorro. Después desde la cuenta de ahorro uno envía x cantidad de dinero al fondo de inversiones y esta se invierte por 60 min y vuelve a la cuenta de ahorro al finalizar esos 60 minutos.
2. Uno envía dinero desde la cuenta normal a la cuenta de ahorro, la que es inmediatamente invertida en el fondo de inversiones y luego de 60 minutos este dinero vuelve a la cuenta normal.
3. Uno envía dinero desde la cuenta normal a la cuenta de ahorro, la que es inmediatamente invertida en el fondo de inversiones que se actualiza cada 60 minutos y esa plata queda invertida hasta que se decida sacarla, momento en que vuelve a la cuenta normal.

¿Cuál es la forma correcta de entender el problema? ¿O es de otra forma?

Saludos,
Mariana

**Comment by mf222** [comment]
La opción 3. Ojo que no hay una respuesta correcta a secas, pero la opción 3 es la única que se acerca a lo que pide el enunciado (las otras dos se alejan del problema).

_En general_ la inversión se queda en el fondo, y no se invierte solo tu aporte, si no que se invierte el fondo completo.

**Comment by marianaortega1** [comment]
gracias!
