### ISSUE TITLE
Ambiente de producción

### ISSUE THREAD

**Issue by juakoke** [IIC2113-2020-2/Recursos#57]
Al subir la app a un Ec2 por ejemplo, debo seguir los mismos pasos ./bin/setup y rails s para correr la app?, pregunto porque la tengo corriendo y no me está reconociendo bien los puertos y quería saber si es problema de esto o algo a modificar en la plataforma

**Comment by mf222** [comment]
Depende de como tengas configurado tu Ec2 y cómo estas levantando la base de datos en ese ambiente (verifica dónde está corriendo). También en development rails corre en el puerto 3000, si quieres hacer que corra y accederlo desde otra máquina tienes que dejarla corriendo en el puerto publico o bien configurar otro puerto y rutearlo. Si el deployment está bien configurado y sospechas que tiene que ver con rails, ejecuta `rails s -e production` en local para simular si existen variables o algunos assets que te están dando problemas.
