### ISSUE TITLE
Token API

### ISSUE THREAD

**Issue by daleal** [IIC2113-2020-2/Recursos#58]
Hola! Quería saber si para la API es necesario usar `jwt` para generar el token o si se espera otra cosa 🤔

**Comment by mf222** [comment]
JWT sería una opción (y buena). Si no, cualquier forma en que generen la "seguridad" de la autenticación de la api se aceptará también si es que lo justifican bien, por ejemplo que ustedes mismos le asignen un string aleatorio y definan si encriptarlo o almacenandolo tal cual, o si piden correo y password del usuario, así como puede haber algun grupo que decida validar al que consulte de otra forma -> como no todos han tomado cursos como web, no seremos estrictos con lo que decidan, con tal de que lo justifiquen (pero ojala que los que si hayan tomado estos cursos sientan culpa por no tomar una decisión más segura, y opten por algo más correcto).

**Comment by daleal** [comment]
OK, me quedó muy claro, muchas gracias!
