### ISSUE TITLE
[Entrega 2] Tema 2 Depositos

### ISSUE THREAD

**Issue by tomascortes** [IIC2113-2020-2/Recursos#59]
Hola!
con nuestro grupo tenemos una duda respecto a los depositos, estos se refieren a en un lugar de la interfaz en la que ingresamos una cantidad y esta se añade automaticamente a los fondos de nuestra normal? 
Y de se así debe existir tanto para ingresar como retirar dinero?
Gracias :)

**Comment by mf222** [comment]
Los depósitos van a la cuenta del usuario. Luego ustedes pueden definir el mecanismo para moverlo al fondo -> si configuran que ese deposito se puede asignar a un fondo o si deciden habilitar otro formulario donde el usuario pueda colocar la cantidad que quiere _transferir desde su cuenta a al fondo_. 

La transferencia desde el fondo al usuario (o sacar el dinero del usuario que esta en el fondo) no está entre las features prioritarias, para que lo consideren.
