### ISSUE TITLE
Parte escrita [ENTREGA 1]

### ISSUE THREAD

**Issue by perezpefaur** [IIC2113-2020-2/Recursos#6]
No entiendo bien que debe incluir el informe, refiriéndose a la parte escrita. ¿Debo explicar los diagramas con palabras? ¿Tengo que hacer una explicación del software y apoyarme con los diagramas?

**Comment by mf222** [comment]
Hola @perezpefaur,

Debes hacer la **documentación inicial**, piensa que le pasaras esto a tus compañeros, ¿qué crees que deberías informarles sobre la aplicación que estás haciendo?. Quizás lo primero es contarles que estás haciendo (una introducción por ejemplo, comentándoles de qué trata, en unas cuantas frases). Luego explicarles la arquitectura, los componentes y las vistas. Los diagramas deberían ser entendibles por si mismos, no se evaluará que estén explicados en palabras.

En el repo base les di la opción de intentar hacer la documentación más enfocada al software y no como informe "típico de tarea universitaria" https://github.com/IIC2113-2020-2/repo-base/tree/master/docs

Finalmente no les estoy pidiendo 3 imágenes sueltas, si no que lo enfoquen a un pequeño informe o readme que explique lo que harán https://github.com/IIC2113-2020-2/Recursos/blob/master/Enunciados%20Proyecto/R%C3%BAbrica%20Entrega%201.pdf

**Comment by arpincheira** [comment]
Hola, en la rubrica de la Entrega 1 se menciona que debemos describir la solución en cuanto a arquitectura, en donde dice que se recomienda seguir una diagramación UML. A que se refiere esto exactamente? A escribir un documento en donde hablemos de la arquitectura que usaremos en el proyecto o a hacer un diagrama UML(Como uno de despliegue), en el que mostremos como va a estar estructurada finalmente la aplicación?
