### ISSUE TITLE
[Entrega 2] Tema 2: Retiro dinero de fondo de inversiones

### ISSUE THREAD

**Issue by tomascortes** [IIC2113-2020-2/Recursos#60]
Hola!
Para el fondo de inversiones no se especifica como hacer retiro de este fondo a nuestra cuenta normal, por lo que no sabemos si esto no debe ser implementado?

Gracias :)

**Comment by mf222** [comment]
No está en las features prioritarias por lo mismo. Es un _nice to have_ si lo implementan, pero no tiene puntaje asignado base para la revisión.

Esto es porque dependerá de cómo programen la solución, si lo hacen a través de transferencias, el retiro les saldría directo y era una feat fácil. Pero si hacen otro tipo de flujo, mejor no se compliquen.
