### ISSUE TITLE
[Entrega 2] Tema 1: Flujo de transacciones

### ISSUE THREAD

**Issue by matioprts** [IIC2113-2020-2/Recursos#61]
Hola, quería saber un poco que se espera para la implementación de la compra/venta de la moneda del exchange.

Particularmente si las transacciones de compra/venta es usuario a usuario, o puede realizarse compras y ventas a una especie de pozo común de la moneda.

En el caso del pozo, la compra se realizaría desde los CLP de la cuenta hacia los BTF del pozo común, pero en la venta desde el pozo común de BTF hacia el CLP, esta debe ser validada posterior una compra hacia el pozo común de BTF o se puede asumir una transferencia de CLP automática al momento de la venta?

**Comment by mf222** [comment]
Tomen los supuestos necesarios, pero recuerden validarlos con sus ayudantes a cargo.
