### ISSUE TITLE
[Entrega 2] Uso de lintern

### ISSUE THREAD

**Issue by tpcantergiani** [IIC2113-2020-2/Recursos#63]
Hola!
En las buenas practicas se evaluara el uso de lintern, como rubocop?
Que lo corri en el repo base, pero me da algunos offenses, que vienen del codigo base.
En el caso de que si se evalue, estos afectaran?
Gracias!

**Comment by mf222** [comment]
Hola,

Se evaluaran sobre el **código nuevo** las buenas prácticas y código legible, la evaluación no será sobre el código base (no se preocupen en arreglar errores de lint del código base). En ese sentido, sí se evaluará que el código este bien escrito. 

La recomendación es que usen rubocop para el código que escriban, es la forma más eficiente de saber (y aprender) si lo que están escribiendo está bien o mal.
