### ISSUE TITLE
[Entrega 2] Uso de Docker

### ISSUE THREAD

**Issue by tfflores** [IIC2113-2020-2/Recursos#64]
Hola,

Si bien con mi grupo hemos trabajado normalmente hasta ahora, teníamos una duda con respecto a Docker. Básicamente no tenemos claro si al hacer el setup inicial (siguiendo los pasos del Readme del proyecto) estamos ya creando un contenedor de Docker.  Pregunto esto porque al intentar correr el comando docker-compose build, la consola simplemente responde con el mensaje "postgresql uses an image, skipping" y no hace nada más.

**Comment by mf222** [comment]
Si no lo están usando puede que el contenedor no funcione. Diría que el contenedor default del proyecto solo hace una imagen de las bases de datos, si quieren dockerizar toda la aplicación tienen que configurarlo. De cualquier forma el uso de docker es optativo, pero altamente recomendado.
