### ISSUE TITLE
[Entrega 2] Duda sobre contabilidad de las transacciones hechas

### ISSUE THREAD

**Issue by fncabrera** [IIC2113-2020-2/Recursos#67]
Hola! 

En la rubrica de la entrega 2 uno de los _items_ es "Mantiene correctamente la contabilidad de las transacciones hechas". ¿Que se espera exactamente para obtener los 10 puntos? Inicialmente pensé que era simplemente llevar un historial de las transacciones pero según la rubrica eso solo es 8 puntos. ¿Quizás que las transacciones hagan sentido con el saldo actual? ¿o algo más?

Gracias!

**Comment by mf222** [comment]
Que sea fácil responder la pregunta "tengo X plata debido a esta suma y resta de transacciones". No es necesario que exista un flujo de caja como tal a nivel de código tratando de imitar la contabilidad; pero si debe existir en la modelación algo que haga mantenga de forma trazable este conteo.

Si modelaron bien lo que aparece en el front, probablemente en backend hicieron algo de este tipo.
