### ISSUE TITLE
[Entrega 2] Usabilidad Frontend

### ISSUE THREAD

**Issue by Marialuisaclaro** [IIC2113-2020-2/Recursos#68]
En el enunciado se menciona que opcionalmente se puede facilitar la usabilidad del frontend usando ​correctamente​ herramientas externas sobre javascript y el css. ¿A que se refiere esto? ¿Usar bootstrap sería una de estas herramientas externas? ¿O tenemos que hacer nuestros propios css?

Gracias!

**Comment by mf222** [comment]
Se refiere a que usen lo que quieran para hacer mejor el frontend. No reinventen la rueda escribiendo todo el CSS.

Ojo siempre que sea uso correcto, si sacan templates free y los implementan mal (mucho css o html que no se use) o si usan mal bootstrap no se va a considerar como buen uso, es pésima práctica añadir código que no se usara o que este mal implementado, y esto suele pasar cuando se integra css externo o se usan templates sin mucho conocimiento previo. 

Este punto también los invita a jugar con frameworks y librerias de js, no solo css.
