### ISSUE TITLE
[Patrones][I2] Preguntas para la I2

### ISSUE THREAD

**Issue by perojas3** [IIC2113-2020-2/Recursos#71]
Tengo las siguientes preguntas para la I2. Algunas son de patrones.

De materia de la I1 (entra retroactivamente):

1.- En la descripción del curso está esta frase “¿Cómo es posible tomar decisiones sobre un proyecto sin involucrarse de forma integral en el proceso?”. ¿A qué se refiere con “involucrarse de forma integral en el proceso”?

2.- Sobre los principios fundamentales, está la Abstracción. Esta debe poseer Suficiencia y Completitud. ¿Que significa que una abstracción sea suficiente y completa?

De la mataría nueva (I2):

3.- En los code smells se encuentran los los “Object-Orientation Abusers”. Uno de ellos es el “Switch Statements”. Lo que me confunde es la clasificación, pues esto también ocurre en lenguajes como C, que no tienen objetos. ¿Porque cuenta como un “Object-Orientation Abusers”?

4.- Otro “Object-Orientation Abusers”. ¿Por qué “Refused Bequest” es un problema? Digo, no veo porque que una subclase utilice parámetros o funciones de una superclase es un problema. Digo, ¿No es la idea OOP?

5.- En los “Code Smells” de tipo “Dispensables”, el “Lazy Class”, especifican como uno de los motivos “Uso de generadores”. ¿A que se refiere?

6.- En otro Code Smells” de tipo''Dispensables”, ''Data Class”. Aquí no entiendo muy bien porqué es un problema. Específicamente porque en algunos frameworks de Arquitectura por Componentes(React, Flutter) son muy usadas las “Data Class”, y por eso me cuesta verlas como un problema.

7.- En Refactoring, la “Rule of Three”. No entiendo el paso 2, la segunda vez que haces algo. ¿En qué consiste?

Ahora sí patrones:

8.- En el “Factory Method”. No entiendo el concepto. ¿El “factory” crea clases nuevas?

9.-No entiendo el objetivo del patrón “Builder”. ¿Por qué es necesario que un objeto cree un objeto de otra clase en vez de usar el mismo constructor de la clase?

10.- El patrón ”Adapter” tiene el scope de ser un patrón de Clase y Objeto simultáneamente. Es el único que hace esto. ¿Porqué?

11.- En el  patrón “Iterator”. No entiendo la referencia mutua entre el agregador y el iterador.

12.- En el  patrón “Iterator”(otra vez). Me confunde el objetivo del patrón. ¿Porqué se querría ocultar la implementación de la iteración?

13.- En el patrón “State”. ¿Cuál es el objetivo de este patrón?

14.- En el patrón “Strategy”. ¿Usando programación funcional, no lo haría innecesario?

15.- En el patrón “Visitor”. Tampoco entiendo el objetivo de este patrón ¿Cuál es?

Y una última pregunta de Arquitectura de Software

16.- No entiendo “Blackboard”. ¿Nos podría dar un ejemplo?

**Comment by mf222** [comment]
> 1.- En la descripción del curso está esta frase “¿Cómo es posible tomar decisiones sobre un proyecto sin involucrarse de forma integral en el proceso?”. ¿A qué se refiere con “involucrarse de forma integral en el proceso”?

Forma integral -> que abarca la totalidad de las áreas del ser humano. Como el software es algo humano, no puede aislarse a solo una solución técnica y acotada de la situación, si no que el diseño tiene que tener en consideración el contexto actual y las implicancias mismas del problema.

> 2.- Sobre los principios fundamentales, está la Abstracción. Esta debe poseer Suficiencia y Completitud. ¿Que significa que una abstracción sea suficiente y completa?

Que a pesar de abstraerse, cumpla con los mínimo esperado para funcionar (suficiencia) y no deja de resolver el problema dejándolo a medias (completitud).

> 3.- En los code smells se encuentran los los “Object-Orientation Abusers”. Uno de ellos es el “Switch Statements”. Lo que me confunde es la clasificación, pues esto también ocurre en lenguajes como C, que no tienen objetos. ¿Porque cuenta como un “Object-Orientation Abusers”?

La definición viene principalmente porque los lenguajes orientados a objetos están más obligados a usar Switch Statements, ya que los lenguajes más antiguos OO, no podían hacer un mapping directo de variables a funciones de forma nativa. Por eso el uso de _Switches_ es más aceptado en OO, pero cae dentro de la definición de code smell ya que hay devs que abusan de estos switches. Hay ocasiones en que no queda otra que usar un switch, pero muchas veces se puede evitar usando alguna clase o re-ordenando el código.

> 4.- Otro “Object-Orientation Abusers”. ¿Por qué “Refused Bequest” es un problema? Digo, no veo porque que una subclase utilice parámetros o funciones de una superclase es un problema. Digo, ¿No es la idea OOP?

**_Recuerda que los code smells son advertencias_**. Son smells de que algo podría estar mal. Entra a la categoria de OO Abusers porque hay devs que tratan de usar este tipo de forma de programar en todo, por eso es un abuso, ya que no se usa con críterio.

> 5.- En los “Code Smells” de tipo “Dispensables”, el “Lazy Class”, especifican como uno de los motivos “Uso de generadores”. ¿A que se refiere?

`rails generate scaffold exchange` -> y de paso creaste 40 archivos, de los cuales 20 con suerte se usaran y la mayoría estarán vacios. En generla hay que usar generadores con moderación.

> 6.- En otro Code Smells” de tipo''Dispensables”, ''Data Class”. Aquí no entiendo muy bien porqué es un problema. Específicamente porque en algunos frameworks de Arquitectura por Componentes(React, Flutter) son muy usadas las “Data Class”, y por eso me cuesta verlas como un problema.

**_Recuerda que los code smells son advertencias_**.  En este caso hace referencia al exceso de clases "vacias" o sin mucha justificación.

> 7.- En Refactoring, la “Rule of Three”. No entiendo el paso 2, la segunda vez que haces algo. ¿En qué consiste?

La primera vez que haces algo pero es un esfuerzo refactorizar, mejor hazlo la segunda vez que sientas que estas repitiendo el código. No sobrecomplejizar la solución inmediatamente, pero a medida que te des cuenta que se necesita.

> 8.- En el “Factory Method”. No entiendo el concepto. ¿El “factory” crea clases nuevas?

Sí y no, en teoria el factory es el credor, y el que instancia por primera vez el FactoryMethod(). Pero ojo que el que termina instanciando es el ConcreteFactory o ConcreteCreator, que hereda del factory inicial y puede darle esta instancia luego. En este ejemplo se nota clara la diferencia, el array es de tipo Creator, pero las instancias son de distintos  ConcreteCreator. Eso le permite que sus métodos tengan lógicas distintas, pero ser usados de forma similar:

![image](https://user-images.githubusercontent.com/5504289/98856599-8b619d00-243c-11eb-89aa-882be76cfa30.png)


Mañana sigo.

**Comment by jpsiegel** [comment]
Me sumo a la pregunta 15 de Pablo, no me quedó tan claro.
Gracias

**Comment by mf222** [comment]
> 9.-No entiendo el objetivo del patrón “Builder”. ¿Por qué es necesario que un objeto cree un objeto de otra clase en vez de usar el mismo constructor de la clase?

Porque si usas el mismo constructor, podrías terminar llenándolo de parámetros o bien con código complejo de if-else. Piensa que el patrón builder está pensado para construir objetos complejos, pero que entre si tienen variaciones, sin embargo la lógica de creación de cada objeto sigue siendo la misma; piensa por ejemplo que para hacer una bebida gaseosa embotellada hay 3 pasos: sacar una botella vacia, rellenar con el líquido de la bebida, cerrar la tapa. Ahora, la embotelladora tiene 3 tipos de tamaño de botella vacia (1 litro, 1,5 y 3 ) y además embotella dos tipos de gaseosa: Pepsi y Crush. El builder será el mismo para todos, pero los pasos intermedios podrían ser definidos en el momento, para sacar por ejemplo una bebida Crush de 1,5 litros y una bebida Pepsi de 3lt.

> 10.- El patrón ”Adapter” tiene el scope de ser un patrón de Clase y Objeto simultáneamente. Es el único que hace esto. ¿Porqué?

Porque afecta a la estructura de la clase (para usar adapter tienes que entrar a la estructura del objeto para poder crearlo), pero luego cuando tengas la instancia permite la configuración de los objetos y usarlos o definirlos como instancias similares. En ese sentido es un patrón versátil, pero a la vez complejo en que la adaptación implicará más código.

> 11.- En el patrón “Iterator”. No entiendo la referencia mutua entre el agregador y el iterador.

El agregador (Aggregate) es la interfaz de la **colección** concreta. La gracia es que el iterador concreto usa el agregador definiendo el agregador concreto para poder iterarlo. Mira en el código de acá abajo:

![image](https://user-images.githubusercontent.com/5504289/98995227-cbde1b00-250f-11eb-9f39-de8412e77e60.png)

Primero se crea la colección que se iterará, y luego en base a esa colección se crea un iterador. Por eso hace sentido la referencia cruzada, por que el iterador existe solo para esa colección, y la colección es iterada por ese iterador (parece trabalenguas, pero creo que se me entendio).

> 12.- En el patrón “Iterator”(otra vez). Me confunde el objetivo del patrón. ¿Porqué se querría ocultar la implementación de la iteración?

Más que ocultar, es abstraerse de la forma en la que se itera una colección. La colección en el mejor de los casos es una lista y se itera de forma líneal. Pero como se ve en Estructuras de Datos, una lista se puede recorrer de otras formas también derrepente te interesa que se recorra desde el medio y vaya saltando de index en index hasta el final. O puede que tu colección no sea líneal, si no que sea un árbol, ahí las formas de iterar pueden ser distintas. Entonces la gracia de este patrón es que mantiene una consistencia en las formas de recorrer (iterar) una colección.

> 13.- En el patrón “State”. ¿Cuál es el objetivo de este patrón?

Está pensado cuando la cantidad de estados de un objeto es finita. Entonces, te permite manejar las transiciones entre estados, sin hacer un if-else gigante, si no que logrando que cada estado sea consciente de sus propias transiciones. Entonces, añadir un nuevo estado no sería costoso, ni implicaría muchas modificaciones extras al código.

> 14.- En el patrón “Strategy”. ¿Usando programación funcional, no lo haría innecesario?

Claro, usas un callback y cumples la misma función. Al final tus _estrategias_ serían las mismas funciones.

> 15.- En el patrón “Visitor”. Tampoco entiendo el objetivo de este patrón ¿Cuál es?

Esta pensado para clases que no puedas modificar su comportamiento o estructura, pero necesitas usarlas. Por eso creas un visitor. En general el uso obedece más a quitarle funcionalidades o comportamientos a clases que prefieres no modificar, que a una problematica clara como en otros patrones. Por eso mismo también no es tan usada, es más condicional a si puedes o no modificar la clase que se "visitará". Algunos casos en los que no puedes modificar, o no conviene, es cuando la clase que necesitas es muy compleja o también cuando estás usando algún otro patrón y no quieres mezclarlos.

> 16.- No entiendo “Blackboard”. ¿Nos podría dar un ejemplo?

Este viene del mundo de IA. Por ejemplo, imaginate tienes un modelo de reconocimiento de lenguaje natural. La forma en que entrenas el modelo estará en un componente separado que el cliente que lo consume. A eso apunta Blackboard, a tener este "pizarron de información y algoritmos" que se pueda usar aparte para consultar.

**Comment by NicolasLahsen** [comment]
Profe tengo una duda del patrón Factory. Si por ejemplo, mis concreteCreators consumen un recurso en común, o deben dejar una constancia/historial de lo que se ha creado, ¿se pueden almacenar en una clase nueva, externa al patrón? Si por ejemplo tuviese una clase Creator que hiciese autos, y mis fábricas concretas hiciesen modelos específicos, ¿está bien crear una clase que los contenga, junto con estos recursos que consumen (partes, por ejemplo)? O esta información debería estar en alguna parte "dentro del patrón" ?

**Comment by mf222** [comment]
> Profe tengo una duda del patrón Factory. Si por ejemplo, mis concreteCreators consumen un recurso en común, o deben dejar una constancia/historial de lo que se ha creado, ¿se pueden almacenar en una clase nueva, externa al patrón? Si por ejemplo tuviese una clase Creator que hiciese autos, y mis fábricas concretas hiciesen modelos específicos, ¿está bien crear una clase que los contenga, junto con estos recursos que consumen (partes, por ejemplo)? O esta información debería estar en alguna parte "dentro del patrón" ?

Creo que, en mi opinión, trataría de dejarlos dentro del patrón. Esto por la cohesión, me hace sentido que mantengas las responsabilidades de la creación (y por ende, el uso de las partes) dentro del patrón, ya que al final si definen un comportamiento de lo que estas creando. Recuerda que los patrones tienen que conversar con el código que se está escribiendo, dejarlos aislados a nivel de libro no es muy escalable en un problema real complejo. 

Ojo que aquí va mi opinión, un purista de los patrones podría discrepar conmigo. Pero de lo que yo he visto en código, he visto que si se mezclan patrones y si se pueden modificar para adaptarlos.
