### ISSUE TITLE
[I2 Teórico] Pregunta sobre el código

### ISSUE THREAD

**Issue by ValentinaAlvarezG** [IIC2113-2020-2/Recursos#72]
Hola! 
En la pregunta 2 de la interrogación dice usar "tipografía Courier new tamaño 8" para el código,si hago la prueba en markdown, hay algún problema con que utilice el mismo markdown para escribir el código (```)?

**Comment by mf222** [comment]
Jajaja sí, con el markdown basta. Es para aquellos que van a subirla en un word. Lo importante es que el código sea legible.

**Comment by ValentinaAlvarezG** [comment]
Ah ok, gracias! Solo quería asegurarme jajaja.
