### ISSUE TITLE
[I2 Teórico] Tipografía Courier new tamaño 8

### ISSUE THREAD

**Issue by rodobkn** [IIC2113-2020-2/Recursos#73]
Hola!

Quisiera saber a que se refiere con subir el código en "tipografía Courier new tamaño 8"?

Puedo escribir el código en Visual Studio Code, y luego tomarle un pantallazo así como sale en la prueba? Honestamente ni si quiera se donde cambiar el tipo de letra en el Visual Studio Code.

Si me podría aclarar cómo usted transformaría su código a ese tipo de letra, sería genial. O si se puede elegir cualquier tipo de letra con tal que se entienda.

PD: Si quisiera subir mi prueba ahora, no aparece en canvas la opción de subirla.

Saludos!

**Comment by mf222** [comment]
Ojala no el pantallazo, porque se puede perder la calidad o las imágenes pueden quedar muy pequeñas. **Lo importante es que tu código sea legible**. Por favor sube el texto, tal de que el ayudante no tenga problema en leerlo.

Mi truco para lograr ese tipo de letra, es copiar desde visual studio code el código, y pegarlo tal cual en el doc (ctrl + c y ctrl + v).

Saludos

**Comment by arpincheira** [comment]
Hola, una consulta, si estoy trabajando en latex puedo utilizar verbatim?

Se vería de la siguiente manera: 
![image](https://user-images.githubusercontent.com/37157550/99122843-d961d680-25dd-11eb-8eab-71da3347d1bd.png)

**Comment by mf222** [comment]
> Hola, una consulta, si estoy trabajando en latex puedo utilizar verbatim?
> 
> Se vería de la siguiente manera:
> ![image](https://user-images.githubusercontent.com/37157550/99122843-d961d680-25dd-11eb-8eab-71da3347d1bd.png)

Mmm pasable 👍
