### ISSUE TITLE
[I2 Teórico] Pregunta 2 - Bug o Feature?

### ISSUE THREAD

**Issue by yerkko** [IIC2113-2020-2/Recursos#74]
En la línea 69 de bad_code.rb se lee:

```rb
while enemies.map(&:hp).reduce(0, :+) > 0 || (mando.hp <= 0 || baby.hp <= 0)
```

Indicando que la simulación corre mientras se de la condición de los enemigos o mando esté muerto o baby esté muerto. Este es comportamiento deseado o un bug ? 🤔

**Comment by mf222** [comment]
¿El bug es porque se cae? Si se cae, arréglenlo.

Tiene que funcionar la simulación si se mueren los enemigos o si se muere alguno de los del team mando/baby.

**Comment by LuisFros** [comment]
El tema es que si se mueren mando y baby, la simulacion sigue corriendo.

**Comment by LuisFros** [comment]
Tenemos que arreglar la logica o asumimos que la logica presentada es la correcta?

**Comment by mf222** [comment]
No añadan ninguna feat extra, por lo tanto no arreglen el loop. Arreglen si se les cae al compilar, ya que debería correr.
La idea de refactorizar es apuntar a mantener el mismo comportamiento, arreglar algo se escapa del scope.

**Comment by LuisFros** [comment]
Perfecto, gracias!

**Comment by yerkko** [comment]
Thank you 🐧
