### ISSUE TITLE
[I2 Teórico] Aplicación de un patrón de diseño 

### ISSUE THREAD

**Issue by tfflores** [IIC2113-2020-2/Recursos#75]
Hola, 
Tenía una duda bastante puntual. Revisando un patrón en específico, identifiqué una diferencia entre el ejemplo de su aplicación (en C#) en Refactoring Guru vs. el ejemplo que aparece en DoFactory. En el primero utilizan interfaces como "base" que son extendidas por clases concretas, mientras que en el segundo utilizan clases abstractas y las clases concretas heredan de ellas. ¿Puedo asumir que cualquiera de los dos _approach_ se considera correcto en la revisión? (Mientras se respete la estructura del patrón, evidentemente).

**Comment by mf222** [comment]
Si, tal como mencionas lo importante es respetar la estructura del patrón.
