### ISSUE TITLE
[I2 Teórico] Pregunta 2

### ISSUE THREAD

**Issue by stmorales** [IIC2113-2020-2/Recursos#76]
Hola! 

En el código los enemigos nunca atacan. Asumimos que en algún minuto lo harán o la funcionalidad del Main ya está 100% definida?

Gracias

**Comment by mf222** [comment]
No añadan funcionalidades, solo hagan refactoring.

**Comment by Dnpoblete** [comment]
Hola, respecto a esto mismo, me queda la duda de si se pueden eliminar funcionalidades si es parte del refactoring, o si en ese caso tampoco se puede.

Muchas gracias :smile:

**Comment by mf222** [comment]
> Hola, respecto a esto mismo, me queda la duda de si se pueden eliminar funcionalidades si es parte del refactoring, o si en ese caso tampoco se puede.
> 
> Muchas gracias 😄

No eliminen funcionalidades (y tampoco traten de añadir). Pueden borrar _funciones_ para refactorizarlas, pero manteniendo la estructura y el **comportamiento** de la aplicación.
