### ISSUE TITLE
[I2 Teórica] Pregunta 3

### ISSUE THREAD

**Issue by stmorales** [IIC2113-2020-2/Recursos#77]
Hola! Me surge una duda, los managers, officers y supervisors pertenecen a un evento en específico o pertenecen a todos los eventos?

Gracias

**Comment by mf222** [comment]
Los managers, officers y supervisors son tipos de usuarios.

**Comment by stmorales** [comment]
Si, perfecto. Pero me imagino que un usuario es manager de un evento. Porque hay dos opciones:

1. Los usuarios son managers/supervisors/officers de algunos eventos en especifico por lo que un evento contiene a estos y ellos son notificados cada una hora según ese evento en especifico.

2. Todos los usuarios son notificados de todos los eventos cada una hora.

Gracias!

**Comment by mf222** [comment]
> Todos los usuarios son notificados de todos los eventos cada una hora.

**Comment by stmorales** [comment]
Gracias
