### ISSUE TITLE
[I2 Teórico] Pregunta 3

### ISSUE THREAD

**Issue by ifieldhouse** [IIC2113-2020-2/Recursos#78]
Con lo siguiente

> implemente ​solamente​ la lógica de la notificación a los usuarios

¿Se refiere a notificación como sustantivo o como verbo? ¿Debemos implementar un componente que notifique a los usuarios según los eventos que le lleguen? ¿O debemos implementar la notificación en sí: el mensaje que les escribiremos a los usuarios?

**Comment by mf222** [comment]
Ambos, pero abstrayéndote de los detalles. Por ejemplo, el mensaje en si no interesa, ya que tampoco está especificado cómo se enviaría el mensaje. Lo que si está especificado son los componentes que se relacionan.
