### ISSUE TITLE
Dudas Entrega 1 (Banco)

### ISSUE THREAD

**Issue by meretamal** [IIC2113-2020-2/Recursos#8]
Hola, nos quedaron algunas dudas en cuanto a la app del banco:

1. ¿Un usuario puede tener más de una cuenta bancaria?
2. Para los _wireframes_, ¿es la idea que no sean muy detallados, o podemos meterle empeño y que queden notables 🙈 ?

Saludos y que tengan un increíble fin de semana 😁

**Comment by cnscheihing** [comment]
Hola @meretamal!

> 1. ¿Un usuario puede tener más de una cuenta bancaria?

No, es una única cuenta por usuario (asociado a su correo o RUT). Esto aplica tanto para la aplicación del banco como para Bitfake.

> 2. Para los wireframes, ¿es la idea que no sean muy detallados, o podemos meterle empeño y que queden notables 🙈 ?

La idea es que sea detallado respecto a los elementos que tendrá la página, sus interacciones y el flujo, de manera que al tomar esas decisiones en esta etapa les permita tener un entendimiento común y hacer el proceso de desarrollo más rápido y directo. 

Por otro lado, no se exige mucho detalle en cuanto al diseño gráfico de la página (como puedes ver [aquí](https://www.mockplus.com/blog/post/wireframe-mockup-prototype-selection-of-prototyping-tools)). Ahora bien, si quieren avanzar en eso también, igual pueden hacerlo!

Espero haberte ayudado!
Saludos

**Comment by meretamal** [comment]
Muchas gracias 😁
