### ISSUE TITLE
[I2 Teórica] Preguntas 3 y 4

### ISSUE THREAD

**Issue by mistico0121** [IIC2113-2020-2/Recursos#81]
Hola, me quedan un par de dudas de estas 2 preguntas.

### Pregunta 3:

Si escribo código, puedo simplemente usar pseudocódigo? O se espera que usemos Ruby o C++?

### Pregunta 4:
No entiendo muy bien la modelación de las clase. Es el cliente una clase de la cual están heredando las clases Google y Facebook? 
Las clases Google y Facebook en el código se refieren a su implentación dentro de la app, o se refiere a Google y Facebook en sí?

Eso, muchas gracias, perdón lo tarde :(

**Comment by mf222** [comment]
> Pregunta 3

Ruby o C#, no pseudo-codigo, a está altura y estando en el computador que programen la solución es mejor para ustedes.

> Pregunta 4

Es la implementación de esos clientes dentro de la app, por los nombres si están relacionados a Google y Facebook. Esto está sacado de una aplicación real.
