### ISSUE TITLE
[Ejercicio I2 Práctico] Dudas enunciado

### ISSUE THREAD

**Issue by kpribbeck** [IIC2113-2020-2/Recursos#82]
Hola! Leí el enunciado del ejercicio práctico y quedé con una serie de preguntas, la verdad no lo entendí mucho. La primera parte es bastante directa, se ingresa un número y tengo que generar tantos colores como el número ingresado, pero después no me queda claro cómo seguir. Dice que usando la una API tengo que generar una paleta de 3 colores, pero después habla de mostrar las 3 paletas generadas (no serán los 3 colores de la paleta?). Tampoco me queda claro qué relación tiene esto con los colores generados inicialmente. Tengo que usar estos colores para crear la paleta? si se usan los mismos, qué pasa si tengo menos de 3? o más? En el ejemplo mostrado se ingresa un 3 y se retornan 3 paletas, significa que con cada color random tengo que generar una triada? o es solo coincidencia que calzara el número?

**Comment by perezpefaur** [comment]
Tengo la misma duda

**Comment by pdesolminihac** [comment]
Según lo que entendí yo es:

1. Pedir un número que indica la cantidad de colores.
2. Crear un color en hex de la manera que uno prefiera.
3. Usando el numero de cantidad de colores y el color generado, utilizar la API para obtener la cantidad de colores que se piden de una paleta que genera la API a partir del color.

**Comment by dmelberg** [comment]
Logré dejarlo como muestra el ejemplo y difiero un poco de @pdesolminihac en el punto 3. La api recibe ciertos parámetros para el GET, entre ellos el "mode"  y "count", (con esto puedes generar paletas de x colores a partir de un color base -- eso está en la documentación de la API). Lo que pide, como entendí yo, el ejercicio, es generar cantidad_que_pide_el_usuario colores "hex" base, y para cada uno generar un "scheme" (aka una paleta de 3 colores que te devuelve la api). En este sentido como dice @kpribbeck sería por cada hex generar una triada con la api.

**Comment by mf222** [comment]
El usuario te da un número entero. En el ejemplo es 3, pero para evitar confusiones, digamos que es 4.

Generas 4 colores en hex.

Con cada uno de esos colores en hex, creas una paleta en la api utilizando el tipo triada. Como generaste 4 colores, tienes que generar 4 paletas distintas, cada una con otros 2 nuevos colores que te indicará la api.

Una triada es una paleta de 3 colores que tienen la misma distancia (forman un triangulo equilatero). Entonces cada una de tus paletas creadas con triadas tendrá uno de estos colores autogenerados como un vertice del triángulo.

**Comment by B-Dominguez** [comment]
Hola profe, cuando a la API uno le pasa una semilla, genera una triada de tres colores (distintos todos de la semilla). Entonces está bien usar esos tres y descartar la semilla?

**Comment by arpincheira** [comment]
Hola, tengo la misma pregunta que @B-Dominguez

**Comment by mistico0121** [comment]
Yo tambien tengo esa misma duda

**Comment by Cadagan** [comment]
(Por si no pudieron ir a la clase de hoy) Dijeron recién que consideremos esos 3 colores como la triada, y filo con la seed misma :raised_hands::raised_hands::raised_hands:
