### ISSUE TITLE
[Ejercicio Práctico 2] Algoritmo hex colors

### ISSUE THREAD

**Issue by nfbalbontin** [IIC2113-2020-2/Recursos#83]
Hola! Qué tal? 
En el enunciado del ejercicio sale, "El **algoritmo** para generar los hex queda a tu criterio, pero considera que deben ser colores válidos". Por lo tanto, ¿Es necesario un algoritmo para generar los colores o simplemente se puede llamar a estos colores predefinidos a partir de valores hex que uno decide? y si no puede ser de esta forma, ¿De qué manera se espera que se generen los colores a partir de valores hex? ¿Según qué tan bajo el número qué tan claro el hex y a la inversa? 
Saludos!

**Comment by mf222** [comment]
Se deben crear aleatoriamente, **no hardcodear colores** (no hagas una lista con X cantidad de elementos hex, del tipo `["#FFFFFF", "#000000"]`).

> ¿De qué manera se espera que se generen los colores a partir de valores hex? ¿Según qué tan bajo el número qué tan claro el hex y a la inversa?

[https://es.wikipedia.org/wiki/Colores_web](https://es.wikipedia.org/wiki/Colores_web)

Cuando trabajan en web, los colores se suelen representar como hex. `#FFFFFF` es blanco por ejemplo. Sabemos que es blanco porque los colores se pueden definir en base a los 3 colores primarios, en RGB (RED, GREEN, BLUE). Lo que dice la teoria de colores web es que se definen "qué tanto tienen de un color" de esta forma `#RRGGBB`. Por lo tanto, el valor de rojo del `#FFFFFF` es `FF`, así como el verde y el azul. En caso del color `#AD45E1` -> `AD` es el rojo, `45` la cantidad de verde, y `E1` la cantidad de azul.

¿Cómo se entienden esas letras y números como cantidad? Generalmente nosotros usamos representaciones en base 10 (los digitos del 0 al 9 forman nuestro sistema numérico, y se elevan a la potencia en base decimal). Lo que hacemos con los colores es usar hexadecimal.

La base hexadecimal usa 16 representaciones (del 0 al 9 y del A al F; siendo 15 representaciones distintas). Entonces FF te dice que en la posición 0 hay un F (que representaria si los ordenas y les asignas un valor en orden, el decimal 15). En la primera posición lo elevas a la posición:
       F x (16^0) + F x (16^1)
=> 15 x (1) + 15 x (16)
=>  15 + 240
=> 255

Por lo tanto, en cada uno de los canales, rojo, verde y azul, tendría el máximo (#FFFFFF -> FF FF FF -> rgb(255, 255, 255)), logrando así el blanco.

![](https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Synthese%2B.svg/238px-Synthese%2B.svg.png).

A pesar de que te di la explicación de que manera se generan colores desde hex, en el ejercicio no te pido el rgb ni _generar un color entendible por ti_, si no que simplemente se pide el hex, por lo que la generación de estos valores debería ser más simple, comprendiendo cuál es el máximo y el mínimo de las representaciones distintas (del 0 al 9 y del A al F; siendo 15 representaciones distintas) para esta secuencia que es el color. Por lo que el algoritmo más simple, es el que genera random estos valores. Ojo que existen algoritmos para generar hex que te permiten tener una separación del color, ya que al hacer algo totalmente aleatorio, los colores que te generen podrían ser muy similares entre si. Por eso el algoritmo queda a criterio de ustedes, pueden optar por algo fácil, o por algo un poco más desafiante.

**Comment by cotiravanal** [comment]
Hola! podría usar una librería de ruby que genere el hexadecimal o tengo que hacerlo a mano? @mf222

**Comment by Marialuisaclaro** [comment]
Hola @mf222 ! Tengo la misma duda que @cotiravanal. Nose si el algoritmo para generar el hex es parte de lo que nos quiere evaluar en esta parte práctica, o podemos/debemos utilizar alguna librería para "no reinventar la rueda". 

Gracias!

**Comment by mf222** [comment]
Pueden usar una librería. Aunque creo que sería un overkill, dado lo simple de generar el color. Pongan ojo con qué cosas importan.
