### ISSUE TITLE
[Ejercicio práctico I2] Responses de la API

### ISSUE THREAD

**Issue by cacoos** [IIC2113-2020-2/Recursos#84]
Hola!

Muy rara vez me pasa que utilizando la API a veces las response son vacías (error de sobrecarga, supongo). Debemos manejar estos casos? Me ha pasado un par de veces pero no logro replicarlo para ver cómo proceder.

Gracias!

**Comment by mf222** [comment]
Siempre que trabajen con api's tienen que manejar esos casos.
