### ISSUE TITLE
[Entrega 3] (Banco) Conexión a API y Bonus 1

### ISSUE THREAD

**Issue by B-Dominguez** [IIC2113-2020-2/Recursos#85]
Hola!

Con mi grupo trabajamos E1 y E2 en exchange, así que ahora en la E3 nos toca banco. Quisiera saber:

- ¿La conexión al exchange puede ser a un deploy hecho por nosotros de nuestra propia app de la E2? Si no, ¿a dónde deberíamos conectarnos?

- En caso de que conectarse como describí en el punto anterior sí cumpla con lo esperado, ¿también cumple con el Bonus 1:  Conectarse con su propia API?

Gracias!

**Comment by oscars810** [comment]
Nosotros tenemos la misma duda! Pero desde la parte del exchange que nos pasaron. ¿A que bancos se supone que nos debemos conectar?

**Comment by mf222** [comment]
> ¿La conexión al exchange puede ser a un deploy hecho por nosotros de nuestra propia app de la E2? Si no, ¿a dónde deberíamos conectarnos?

Sí, el bonus es sobre su propia E2 si es que hicieron el bonus anterior. En caso contrario, hagan un mock.

> En caso de que conectarse como describí en el punto anterior sí cumpla con lo esperado, ¿también cumple con el Bonus 1: Conectarse con su propia API?

No entendí esta pregunta, pero repito la indicación: si se conectan con su propia API de la entrega anterior, entonces pueden optar por el bonus. En caso contrario, **no hay bonus pero de todas formas tienen que conectarse al mock**.

> Nosotros tenemos la misma duda! Pero desde la parte del exchange que nos pasaron. ¿A que bancos se supone que nos debemos conectar?

Al mismo que hicieron ustedes en la entrega anterior si es que la hicieron bien, o bien van a tener que crear los endpoints necesarios a mano en https://mockapi.io/ (no hay bonus en este caso, si no que es un mínimo esperado que será evaluado)

**Comment by B-Dominguez** [comment]
Me queda claro, gracias!
