### ISSUE TITLE
[Entrega 3] (Banco) Monto y efecto de compra y venta de Bitfake

### ISSUE THREAD

**Issue by B-Dominguez** [IIC2113-2020-2/Recursos#86]
Hola, quisiera confirmar si entendimos bien del enunciado algunos puntos con los que no estamos seguros, relativos a la determinación del monto de compra/venta de Bitfake y su efecto:

- Ahora se siguen generando subidas y bajadas de montos CLP aleatorios del fondo de inversión, solo que éstos montos ahora representan compras o ventas de Bitfake
- La determinación del monto puede ser mediante algún random sencillo
- Si se compra/vende X CLP en BTF's, se debe ajustar el valor de la acción para que el total `#acciones * $acción` baje en X CLP

Gracias!

**Comment by mf222** [comment]
> Ahora se siguen generando subidas y bajadas de montos CLP aleatorios del fondo de inversión, solo que éstos montos ahora representan compras o ventas de Bitfake

Depende de la modelación de la aplicación: si les permite separar las subidas y bajadas aleatorias de la compra y venta entonces no lo reemplacen. En caso de que esté muy acoplado, entonces sí, quiten el comportamiento de las subidas y bajadas aleatorias.

> La determinación del monto puede ser mediante algún random sencillo

Inviertan todo lo que se tenga ahorrado en el fondo. Por eso es fondo riesgoso. De cualquier forma, y si les acomoda dejenlo como una variable que represente el porcentaje y que parta con 1.

> Si se compra/vende X CLP en BTF's, se debe ajustar el valor de la acción para que el total #acciones * $acción baje en X CLP

Sí, tiene que ajustarse el valor de lo invertido por cada usuario. Ojo, que yo esperaría que esto debería estar funcionando más o menos listo de la entrega anterior, eviten salirse del scope de la entrega para no trabajar de más y si identifican que algo no funciona bien de la entrega anterior **tienen que avisar a su ayudante y consultarle** si vale la pena o no solucionarlo.
