### ISSUE TITLE
[I2 ejercicio práctico] - Pauta ejercicio práctico i1

### ISSUE THREAD

**Issue by Cadagan** [IIC2113-2020-2/Recursos#87]
Estimado equipo docente

Mi duda es si de casualidad podrían publicar pronto la **solución tipo pauta del ejercicio práctico de la i1**, para ocuparlo como un buen ejemplo para el ejercicio practico i2.
Considerando que creo que todavía no lo han podido publicar (no se preocupen, es fin de semestre para todo el mundo, se entiende :wink: ) y que no lo pudimos ver en clases, el plazo de entrega de esta parte práctica de la i2 ¿también se mantiene o se va a modificar? 
Gracias de antemano :blush:

**Comment by mf222** [comment]
> ¿también se mantiene o se va a modificar?

Se mantiene. La I1 y la I2 son **independientes** entre sí, no hay correlación. 

Si necesitan más plazo debido a fin de semestre prefiero que lo pidan, en vez de buscar una excusa como que necesitan un _buen ejemplo_. Ustedes ya tienen el feedback de su ejercicio práctico anterior y es un feedback personal para cada uno de sus propios códigos, que es por lejos más útil que un ejemplo de código de un ejercicio que ya pasó.
