### ISSUE TITLE
[I2 ejercicio práctico] - Atributo de clase

### ISSUE THREAD

**Issue by B-Dominguez** [IIC2113-2020-2/Recursos#88]
Hola! En internet encontré que usar un atributo de clase, como un contador, podría ser un _code smell_. Quisiera saber si esto siempre es así y deberíamos preferir alguna implementación que no use atributo de clase. Esto considerando no solo que no recuerdo haber visto éste como un _code smell_ oficial, si no también porque los _code smell_ son solo advertencias y quizás para este caso particular no es problema.

Gracias!

**Comment by mf222** [comment]
Hola Benjamín,

Tal como mencionas, los code smell son advertencias. Dependiendo del tipo de ejercicio el contador podría ser (o no) un indicador de algo más. Recuerda que el code smell es una advertencia de algo mayor, por lo que el contador en si no es el problema. 

Si tienes el link de la página lo puedes enviar para ver por qué era un code smell el contador. Pero si es por atributo de clase, me suena que podría ser un Dispensable, y apuntaría a que a veces no es necesario definir atributos de clase "inutiles" (por ejemplo usar for definiendo ahí el contador). Si el contador es necesario, entonces no sería un Dispansable.

**Comment by B-Dominguez** [comment]
Muchas gracias! Creo que efectivamente debe haber sido como un indicador de un Dispensable.
