### ISSUE TITLE
[I2 ejercicio práctico] Input erroneo por parte del usuario

### ISSUE THREAD

**Issue by tomascortes** [IIC2113-2020-2/Recursos#89]
Hola!
Tenía la duda de que si tenemos que asumir que el input del usuario siempre será correcto, y en caso de que sea erroneo, se debe pedir denuevo o simplemente se termina la ejecución.

Muchas gracias

**Comment by mf222** [comment]
Sí es incorrecto basta con que terminen la ejecución de forma "correcta" (osea, no dejen que se caiga el programa, si no que cortenlo ustedes). No debería costarles más de una línea de código.
