### ISSUE TITLE
Duda Entrega 1 Enunciado

### ISSUE THREAD

**Issue by arpincheira** [IIC2113-2020-2/Recursos#9]
Hola, en la rubrica de la Entrega 1 se menciona que debemos describir la solución en cuanto a arquitectura, en donde dice que se recomienda seguir una diagramación UML. A que se refiere esto exactamente? A escribir un documento en donde hablemos de la arquitectura que usaremos en el proyecto o a hacer un diagrama UML(Como uno de despliegue), en el que mostremos como va a estar estructurada finalmente la aplicación?

Muchas gracias de antemano

**Comment by mf222** [comment]
Si tienes más dudas al respecto, por favor ahondemos en esta issue https://github.com/IIC2113-2020-2/Recursos/issues/6
