### ISSUE TITLE
[I2 Práctico] Bloqueo de API

### ISSUE THREAD

**Issue by tamaralues** [IIC2113-2020-2/Recursos#90]
Hola!
Estoy teniendo un problema con mi tarea, y no estoy pudiendo accedes a la API. Tengo este problema desde ayer y lo que pasa es que me responde siempre con un timeout, pero antes sí me respondía con lo solicitado. Probé con otras API y se me responden , saben qué puede estar ocurriendo?? probé varías cosas pero ninguna me funciono :(

**Comment by mf222** [comment]
Yo acabo de probar y me funciona. Puede que hayas realizado muchas requests simultáneas y te hayan bloqueado la IP. Mi recomendación es que: 

- Prueba con queries simples para corroborar que efectivamente es problema de que la conexión con la api está mal, y no es la query. Recuerda que también te podría dar timeout si tu conexión no es muy buena.
- Si compruebas que todas las queries fallan, prueba cambiandote de red o usando vpn. Si es por bloqueo con eso debería bastar. 
- Aprovecha los timeouts para programar el "qué ocurre si falla la request".

**Comment by nrrosenberg** [comment]
Hola! Estoy teniendo el mismo problema, ante con exactamente el mismo programa funcionaba perfecto y ahora el request a la api no me devuelve nada, hasta el timeout.

**Comment by tamaralues** [comment]
Hola! a mi se me solucionó poniendo la uri completa! 'http://www.thecolorapi.com/scheme?' :)

**Comment by nrrosenberg** [comment]
Buenaa Gracias!
