### ISSUE TITLE
Sobre la presentación de la E3

### ISSUE THREAD

**Issue by ValentinaAlvarezG** [IIC2113-2020-2/Recursos#91]
Hola! para la presentación final, tenemos que " exponer los elementos más relevantes de su trabajo", me queda la duda de si estos elementos son de nuestro trabajo en la entrega pasada o de esta entrega.

Gracias!

**Comment by mf222** [comment]
Puede ser cualquiera de las dos, estaré subiendo en unos minutos un anuncio con la información detallada de lo que se espera.
