### ISSUE TITLE
[Entrega 3] (Exchange) Cantidad de bancos

### ISSUE THREAD

**Issue by tpcantergiani** [IIC2113-2020-2/Recursos#92]
Hola!
En el enunciado del proyecto, aparece que debemos obtener las transacciones de cada banco de inversiones asignados.
La cosa, es que en la entrega anterior, solo se hizo un banco.
¿Podemos suponer que solo hay un banco, o deberiamos generar otras mockapis, ademas de la nuestra?
Gracias!

**Comment by mf222** [comment]
Sí, error de lenguaje, asuman que será solo uno: el banco de su entrega anterior o en caso de que no puedan o prefieran usar el mock, un set de recursos de mockapi.
