### ISSUE TITLE
[Entrega 3] (Exchange) Carga de CLP

### ISSUE THREAD

**Issue by bawas** [IIC2113-2020-2/Recursos#93]
Hola!

Queríamos saber si estamos entendiendo bien la lógica de la carga de CLP. El enunciado dice que el usuario debe conectarse a la API (en nuestro caso mockAPI) y revisar si hay transacciones nuevas con el RUT de dicho usuario.

Estábamos pensando en que para desarrollar lo anterior, bastaba con crear recursos varios en el mockAPI que contengan depósitos aleatorios para algunos RUT, y que cada llamada a la API vaya guardando en la base las transacciones correspondientes, para así poder identificar cuales son nuevas en llamadas siguientes. ¿Es esto lo que se busca?

Gracias!.

**Comment by mf222** [comment]
Creo que si te entendí bien, sí: creen los recursos de cada modelo y generen datos para cada uno. Si no es eso, cualquier supuesto lo documentan.
