### ISSUE TITLE
[Entrega 3] Subir aplicación a servidor

### ISSUE THREAD

**Issue by Marialuisaclaro** [IIC2113-2020-2/Recursos#95]
Hola! 
En el enunciado de la Entrega 3 dice lo siguiente:
- En la primera línea del Readme.md el link a la aplicación levantada en el servidor elegido.
- Documentación en Readme.md del repositorio con información sobre cómo montar ejecutar
la aplicación en local y sobre cómo montar o actualizar la aplicación en el servidor.

Dado que esta entrega es solo de backend, ¿debemos subir solo el backend al servidor? ¿O ya no es necesario?

**Comment by mf222** [comment]
> ¿debemos subir solo el backend al servidor?

No se evaluará levantarlo en el servidor. 

Lo que si se evaluará como ejecutarlo para correrlo y calificar las funcionalidades. Dicho lo anterior, si el ayudante no puede correr su aplicación en local se verán perjudicados y levantar el backend puede facilitar la revisión (pero no es obligatorio)
