### ISSUE TITLE
[Entrega 2/3] Fondo de inversión riesgoso

### ISSUE THREAD

**Issue by jmndoza** [IIC2113-2020-2/Recursos#96]
Hola, en esta entrega nos toca un repo de banco.
Sobre este item, 
> Cada 60 minutos el fondo del banco no debe crecer ni disminuir aleatoriamente. En su lugar, debe comprar o vender BTF en un exchange asignado.

El repo que tenemos no tiene fondo de inversión, la solución que implementaron solo considera un random en el tiempo correspondiente y subir saldo de cuentas existentes, la entrega 2 especificaba esto para banco:

> - El banco tiene un módulo de inversiones. El módulo de inversiones es un fondo de inversión
riesgoso que el banco usa para invertir y así generar ganancias (o pérdidas) proporcionales para todos sus usuarios dependiendo del monto que ha ahorrado.
> - Un usuario puede enviar dinero desde su cuenta al fondo de inversiones. Se registra este valor como ahorro.
> - El banco usa este fondo para invertir. Para efectos de esta entrega, y por simplicidad, este “invertirá 60 minutos”. Esto se traduce en que el fondo crecerá o disminuirá en un factor aleatorio entre [-0.03, +0,03] porcentaje del valor.
> - Si el fondo gana o pierde, se deberá ver reflejado no solo en el fondo total, si no que también en las cuentas de ahorro individuales de cada usuario.

Debemos terminar/reparar esto? pareciera que sí para poder avanzar con la implementación de la inversión en el Exchange.
Preguntas de eso:

> Un usuario puede enviar dinero desde su cuenta al fondo de inversiones. Se registra este valor como ahorro.

quiere decir que en mi cuenta de ahorro, yo deje un % en el fondo? y debo poder verlo desde mi cuenta(el valor $)?? 
cuando hablamos de lo que pierde y gana el fondo, el % reparto es sobre el monto invertido? (lo lógico pareciera que si..)
necesitamos mantener un historial de lo que pasa con el fondo? el usuario también debería tener eso en su historial?
cuando un usuario se crea ( y sus cuentas respectivas) deberíamos enviar dinero al fondo? para que no este vacío al iniciar? o podría ser que solo el fondo nació con $X

(Al escribirlo me di cuenta que es mas de lo que pensaba) Podría ser que el fondo inicia con $X y sobre ese monto se hagan las inversiones, y las ganancias/perdidas sean para todos los usuarios por igual ? por ejemplo asumiendo un porcentaje de la inversión ( todos los usuarios son inversionistas con un 10% de su capital **inicial**, por ej), lo de inicial es relevante, dado que no podríamos mantener persistente **cada** inversión... 
 o quizás que solo se crea el fondo con X dinero y ahí reparte a todos por igual?

Gracias!

**Comment by mf222** [comment]
Te respondo directamente la pregunta inicial:

> Debemos terminar/reparar esto?

No, hagan el mínimo esfuerzo para que pueda funcionar lo que ya existe con las nuevas funcionalidades de la entrega 3. 

Sobre la pregunta: se invierte todo, y el aporte de cada persona se mantiene como un % del total. No se invierte la plata de cada persona por separado, ustedes solo mantienen porcentajes (y los actualizan). Por lo mismo si el fondo gana o pierde, el usuario verá el % de lo que invirtió por la cantidad del fondo en ese momento.
